# Generated by Django 5.2.17 on 2026-08-29 14:31

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ITEM', 'Inventory item'), ('EXPENSE', 'Expense')], db_index=True, max_length=8)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'logistics_category',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('public_id', models.CharField(editable=False, max_length=16, unique=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('amount_minor', models.BigIntegerField(help_text='Integer minor units. Never a float.')),
                ('currency', models.CharField(default='DZD', max_length=3)),
                ('spent_on', models.DateField(help_text='When the money left, not when it was typed in.')),
                ('period_year', models.PositiveIntegerField(db_index=True)),
                ('period_month', models.PositiveSmallIntegerField(db_index=True)),
                ('method', models.CharField(blank=True, max_length=16)),
                ('reference', models.CharField(blank=True, help_text='Receipt or invoice number, if there is one.', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='logistics.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logistics_expense',
                'ordering': ['-period_year', '-period_month', '-spent_on', '-created_at'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logistics_location',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('public_id', models.CharField(editable=False, max_length=16, unique=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('NEEDS_REPAIR', 'Needs repair'), ('DAMAGED', 'Damaged')], db_index=True, default='GOOD', max_length=16)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In use'), ('UNDER_REPAIR', 'Under repair'), ('MISSING', 'Missing')], db_index=True, default='AVAILABLE', max_length=16)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price_minor', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='DZD', max_length=3)),
                ('serial_number', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='logistics.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='logistics.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logistics_item',
                'ordering': ['-updated_at', 'name'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('kind', 'name'), name='uniq_logistics_category_name'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['period_year', 'period_month'], name='logistics_e_period__1a6cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'period_year', 'period_month'], name='logistics_e_categor_e38584_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gte', 0)), name='logistics_expense_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('period_month__gte', 1), ('period_month__lte', 12)), name='logistics_expense_month_in_range'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('period_year__gte', 2000), ('period_year__lte', 2100)), name='logistics_expense_year_in_range'),
        ),
        migrations.AddIndex(
            model_name='logisticsitem',
            index=models.Index(fields=['category', 'status'], name='logistics_i_categor_b330c7_idx'),
        ),
        migrations.AddIndex(
            model_name='logisticsitem',
            index=models.Index(fields=['condition', 'status'], name='logistics_i_conditi_ca6ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='logisticsitem',
            index=models.Index(fields=['location', 'name'], name='logistics_i_locatio_aec419_idx'),
        ),
        migrations.AddConstraint(
            model_name='logisticsitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='logistics_quantity_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='logisticsitem',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price_minor__isnull', True), ('purchase_price_minor__gte', 0), _connector='OR'), name='logistics_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='logisticsitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('serial_number', ''), _negated=True)), fields=('serial_number',), name='uniq_live_logistics_serial_number'),
        ),
    ]
