# Generated by Django 5.2.17 on 2026-08-24 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('kind', models.CharField(choices=[('COURSE_ASSIGNED', 'Assigned to a course'), ('SESSION_REMINDER', 'Next session reminder'), ('ROSTER_CHANGED', 'Class list changed'), ('SCHEDULE_CHANGED', 'Schedule changed'), ('ENROLLED', 'Enrolled in a course'), ('MARKS_PUBLISHED', 'Marks published'), ('PAYMENT_APPROVED', 'Payment approved'), ('PAYMENT_REJECTED', 'Payment rejected'), ('PROOF_REVIEW_NEEDED', 'Payment awaiting review')], db_index=True, max_length=24)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('SMS', 'SMS'), ('EMAIL', 'Email')], default='IN_APP', max_length=8)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=50)),
                ('link_path', models.CharField(blank=True, help_text='Frontend route this notification points at.', max_length=200)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['kind', '-created_at'], name='notificatio_kind_87ba1b_idx')],
            },
        ),
    ]
