# Generated by Django 5.2.17 on 2026-08-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierSequence',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('current_value', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'identifier sequence',
                'db_table': 'core_identifier_sequence',
            },
        ),
    ]
