# Generated by Django 5.2.17 on 2026-08-24 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended'), ('DROPPED', 'Dropped')], db_index=True, default='ACTIVE', max_length=12)),
                ('price_at_enrollment_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='DZD', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enrollments_enrollment',
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['course', 'status'], name='enrollments_course__f8877c_idx'), models.Index(fields=['student', 'status'], name='enrollments_student_885f1d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['CANCELLED', 'DROPPED']), _negated=True), fields=('student', 'course'), name='uniq_live_enrollment_per_course'), models.CheckConstraint(condition=models.Q(('price_at_enrollment_minor__gte', 0)), name='enrollment_price_not_negative')],
            },
        ),
    ]
