# Generated by Django 5.2.17 on 2026-08-24 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_public_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('action', models.CharField(choices=[('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_STATUS_CHANGED', 'User status changed'), ('PASSWORD_RESET', 'Password reset'), ('PASSWORD_CHANGED', 'Password changed'), ('ROLE_GRANTED', 'Role granted'), ('ROLE_REVOKED', 'Role revoked'), ('LOGIN_FAILED', 'Login failed'), ('COURSE_CREATED', 'Course created'), ('COURSE_UPDATED', 'Course updated'), ('COURSE_STATUS_CHANGED', 'Course status changed'), ('PROFESSOR_ASSIGNED', 'Professor assigned'), ('PROFESSOR_UNASSIGNED', 'Professor unassigned'), ('SCHEDULE_CHANGED', 'Schedule changed'), ('ENROLLMENT_CREATED', 'Student enrolled'), ('ENROLLMENT_STATUS_CHANGED', 'Enrolment status changed'), ('MARK_ENTERED', 'Mark entered'), ('MARK_CHANGED', 'Mark changed'), ('MARKS_PUBLISHED', 'Marks published'), ('PAYMENT_CREATED', 'Payment recorded'), ('PAYMENT_APPROVED', 'Payment approved'), ('PAYMENT_REJECTED', 'Payment rejected'), ('PAYMENT_CANCELLED', 'Payment cancelled'), ('PROOF_UPLOADED', 'Payment proof uploaded'), ('PROOF_DOWNLOADED', 'Payment proof downloaded')], db_index=True, max_length=32)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('object_label', models.CharField(blank=True, help_text='Human-readable at the time of the action.', max_length=200)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_log_object__8ccc11_idx'), models.Index(fields=['actor', '-created_at'], name='audit_log_actor_i_91cd96_idx'), models.Index(fields=['action', '-created_at'], name='audit_log_action_7c9e02_idx')],
            },
        ),
    ]
