# Generated by Django 5.2.17 on 2026-08-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_append_only_trigger'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_log_actor_i_91cd96_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='actor',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_public_id', '-created_at'], name='audit_log_actor_p_dfe78d_idx'),
        ),
    ]
