# Generated by Django 5.2.17 on 2026-08-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_STATUS_CHANGED', 'User status changed'), ('PASSWORD_RESET', 'Password reset'), ('PASSWORD_CHANGED', 'Password changed'), ('ROLE_GRANTED', 'Role granted'), ('ROLE_REVOKED', 'Role revoked'), ('LOGIN_FAILED', 'Login failed'), ('COURSE_CREATED', 'Course created'), ('COURSE_UPDATED', 'Course updated'), ('COURSE_STATUS_CHANGED', 'Course status changed'), ('PROFESSOR_ASSIGNED', 'Professor assigned'), ('PROFESSOR_UNASSIGNED', 'Professor unassigned'), ('SCHEDULE_CHANGED', 'Schedule changed'), ('ENROLLMENT_CREATED', 'Student enrolled'), ('ENROLLMENT_STATUS_CHANGED', 'Enrolment status changed'), ('MARK_ENTERED', 'Mark entered'), ('MARK_CHANGED', 'Mark changed'), ('MARKS_PUBLISHED', 'Marks published'), ('ATTENDANCE_TAKEN', 'Register taken'), ('ATTENDANCE_CHANGED', 'Attendance corrected'), ('PAYMENT_CREATED', 'Payment recorded'), ('PAYMENT_APPROVED', 'Payment approved'), ('PAYMENT_REJECTED', 'Payment rejected'), ('PAYMENT_CANCELLED', 'Payment cancelled'), ('PROOF_UPLOADED', 'Payment proof uploaded'), ('PROOF_DOWNLOADED', 'Payment proof downloaded'), ('LOGISTICS_ITEM_CREATED', 'Inventory item added'), ('LOGISTICS_ITEM_UPDATED', 'Inventory item edited'), ('LOGISTICS_ITEM_DELETED', 'Inventory item removed'), ('EXPENSE_CREATED', 'Expense recorded'), ('EXPENSE_UPDATED', 'Expense edited'), ('EXPENSE_DELETED', 'Expense removed'), ('REVIEW_CREATED', 'Review written'), ('REVIEW_UPDATED', 'Review edited'), ('REVIEW_MODERATED', 'Review moderated'), ('ORGANISATION_UPDATED', 'Organisation profile updated'), ('REPORT_EXPORTED', 'Report exported'), ('EXPORT_DOWNLOADED', 'Export downloaded')], db_index=True, max_length=32),
        ),
    ]
