# Generated by Django 5.2.17 on 2026-08-24 12:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Optional second login identifier.', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a phone number in international or local digits, optionally starting with +.', regex='^\\+?[0-9]{6,20}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('primary_role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('RECEPTION', 'Reception'), ('PROFESSOR', 'Professor'), ('STUDENT', 'Student')], max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=16)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_user',
                'indexes': [models.Index(fields=['status', 'primary_role'], name='accounts_us_status_500aca_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('deactivated_at__isnull', True), ('status', 'ACTIVE')), models.Q(('status', 'ACTIVE'), _negated=True), _connector='OR'), name='active_users_have_no_deactivation_timestamp')],
            },
        ),
    ]
