# Generated by Django 5.2.17 on 2026-08-24 14:01

import apps.core.phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Stored in E.164 (+213555123456). Optional second login identifier.', max_length=16, null=True, unique=True, validators=[apps.core.phone.validate_e164]),
        ),
    ]
