# Generated by Django 5.2.17 on 2026-08-24 16:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('QUIZ', 'Quiz'), ('MIDTERM', 'Midterm'), ('FINAL', 'Final'), ('ORAL', 'Oral'), ('HOMEWORK', 'Homework'), ('PARTICIPATION', 'Participation')], default='QUIZ', max_length=16)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('held_on', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessments_assessment',
                'ordering': ['held_on', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('last_changed_at', models.DateTimeField(blank=True, null=True)),
                ('change_count', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.assessment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='enrollments.enrollment')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessments_score',
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['course', 'held_on'], name='assessments_course__b82bf6_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='assessment_max_score_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='assessment_weight_not_negative'),
        ),
        migrations.AddIndex(
            model_name='assessmentscore',
            index=models.Index(fields=['enrollment'], name='assessments_enrollm_d8aeb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentscore',
            constraint=models.UniqueConstraint(fields=('assessment', 'enrollment'), name='uniq_score_per_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='assessmentscore',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='score_not_negative'),
        ),
    ]
