# Generated by Django 5.2.17 on 2026-08-24 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(editable=False, max_length=16, unique=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='DZD', max_length=3)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum enrolments. Blank means uncapped.', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=12)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses_course',
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_role', models.CharField(choices=[('LEAD', 'Lead'), ('ASSISTANT', 'Assistant')], default='LEAD', max_length=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=8)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses_course_professor',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(related_name='courses_taught', through='courses.CourseProfessor', through_fields=('course', 'professor'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='courseprofessor',
            index=models.Index(fields=['professor', 'status'], name='courses_cou_profess_2f784c_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseprofessor',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('course', 'professor'), name='uniq_active_course_professor'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'start_date'], name='courses_cou_status_c0e54f_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='course_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('price_minor__gte', 0)), name='course_price_not_negative'),
        ),
    ]
