import type { Dict } from "./en";

/**
 * Arabic — Modern Standard, with the Algerian administrative vocabulary.
 *
 * Typed against the English dictionary, so a missing key will not compile.
 *
 * Three things worth knowing if you edit this file:
 *
 * 1. The interface is mirrored, not merely translated. `dir="rtl"` on <html>
 *    flips the whole layout, and every physical `left`/`right` utility in the
 *    codebase was replaced with a logical `start`/`end` one so it actually
 *    follows.
 *
 * 2. Numerals are Western (0-9), not Arabic-Indic. That is what `ar-DZ` gives
 *    and what an Algerian ledger, invoice and identity card use. Money and
 *    identifiers stay comparable down a column across all three languages.
 *
 * 3. No letter-spacing anywhere under RTL — the stylesheet zeroes it. Arabic
 *    is a joined script, and spacing the letters of a word pulls the joins
 *    apart.
 *
 * Vocabulary: تسجيل for an enrolment, دفعة for a payment, متربص for someone on
 * a vocational course and مكوِّن for the person teaching it — the words the
 * training sector uses in Algeria, rather than طالب and أستاذ, which belong to
 * a university.
 */

export const ar: Dict = {
  meta: {
    language: "اللغة",
    changeLanguage: "تغيير اللغة",
  },

  common: {
    save: "حفظ",
    cancel: "إلغاء",
    close: "إغلاق",
    confirm: "تأكيد",
    open: "فتح",
    back: "رجوع",
    search: "بحث",
    filter: "تصفية",
    filters: "عوامل التصفية",
    clear: "مسح",
    clearAll: "مسح الكل",
    apply: "تطبيق",
    optional: "اختياري",
    required: "إلزامي",
    loading: "جارٍ التحميل",
    none: "لا شيء",
    any: "الكل",
    all: "الكل",
    yes: "نعم",
    no: "لا",
    more: "المزيد",
    of: "من",
    previous: "السابق",
    next: "التالي",
    retry: "أعد المحاولة",
    toDashboard: "العودة إلى لوحة القيادة",
  },

  roles: {
    OWNER: "المالك",
    ADMIN: "مسؤول",
    RECEPTION: "الاستقبال",
    PROFESSOR: "مكوِّن",
    STUDENT: "متربص",
  },

  status: {
    PENDING: "قيد الانتظار",
    APPROVED: "مُصادق عليه",
    REJECTED: "مرفوض",
    CANCELLED: "ملغى",
    ACTIVE: "نشط",
    COMPLETED: "منتهٍ",
    SUSPENDED: "موقوف",
    DROPPED: "منقطع",
    DRAFT: "مسودة",
    ARCHIVED: "مؤرشف",
    HIDDEN: "مخفي",
    INACTIVE: "غير نشط",
    RUNNING: "جارٍ",
    READY: "جاهز",
    FAILED: "فشل",
    CLEAN: "سليم",
    INFECTED: "مصاب",
    PUBLISHED: "منشور",
    FINISHED: "منتهٍ",
    // Inventory: what state a thing is in, and where it is.
    AVAILABLE: "متاح",
    IN_USE: "قيد الاستعمال",
    UNDER_REPAIR: "قيد الإصلاح",
    MISSING: "مفقود",
    NEW: "جديد",
    GOOD: "حالة جيدة",
    NEEDS_REPAIR: "يحتاج إصلاحًا",
    DAMAGED: "تالف",
    // Attendance: a mark on a register, and the register's own state.
    PRESENT: "حاضر",
    ABSENT: "غائب",
    LATE: "متأخر",
    OPEN: "مفتوحة",
    SUBMITTED: "مسجّلة",
  },

  nav: {
    groupWork: "العمل",
    groupPeople: "الأشخاص",
    groupOversight: "الرقابة",
    dashboard: "لوحة القيادة",
    courses: "التكوينات",
    enrollments: "التسجيلات",
    schedules: "التوقيت",
    grades: "النقاط",
    payments: "الدفعات",
    users: "الأشخاص",
    reviews: "التقييمات",
    notifications: "الإشعارات",
    reports: "التقارير",
    audit: "سجل التدقيق",
    account: "حسابك",
    main: "الرئيسية",
    openNavigation: "فتح القائمة",
    closeNavigation: "إغلاق القائمة",
    navigation: "التنقل",
    toDashboard: "SM Academy — لوحة القيادة",
    logistics: "اللوجستيك",
    attendance: "الحضور",
    settings: "الإعدادات",
  },

  shell: {
    notifications: "الإشعارات",
    notificationsWithCount: "الإشعارات، {count} غير مقروءة",
    unread: "غير مقروءة",
    accountMenu: "الحساب",
    yourAccount: "حسابك",
    signOut: "تسجيل الخروج",
    signingOut: "جارٍ تسجيل الخروج…",
  },

  ui: {
    pages: "الصفحات",
    updatingList: "جارٍ تحديث القائمة",
    chooseOne: "اختر",
    loadMore: "تحميل المزيد",
    loadingPage: "جارٍ تحميل الصفحة",
    loadingRows: "جارٍ تحميل السطور",
    loadingFigures: "جارٍ تحميل الأرقام",
    loadingDetails: "جارٍ تحميل التفاصيل",
    loadingSchedule: "جارٍ تحميل التوقيت",
    unsavedChanges: "تغييرات غير محفوظة",
    serverUnreachable: "تعذّر الوصول إلى الخادم.",
  },

  units: {
    payments: "دفعة",
    people: "شخصاً",
    courses: "تكويناً",
    enrollments: "تسجيلاً",
    reviews: "تقييماً",
    notifications: "إشعاراً",
    students: "متربصاً",
    items: "عنصر",
    expenses: "مصروف",
    months: "شهر",
    registers: "ورقة",
    records: "سجل",
  },

  login: {
    title: "تسجيل الدخول",
    lede: "معرّفك هو المطبوع على بطاقتك. الحسابات تصدرها الأكاديمية — لا يوجد تسجيل عمومي.",
    identifier: "المعرّف أو رقم الهاتف",
    identifierHint: "المعرّف المطبوع على بطاقتك، أو الرقم الذي سجّلته.",
    identifierPlaceholder: "STU-000042",
    password: "كلمة المرور",
    showPassword: "إظهار كلمة المرور",
    hidePassword: "إخفاء كلمة المرور",
    submit: "دخول",
    submitting: "جارٍ الدخول…",
    unreachable: "تعذّر الوصول إلى الخادم. أعد المحاولة.",
    lostPassword:
      "نسيت كلمة المرور؟ اطلب من الاستقبال إعادة تعيينها — يمكنهم إصدار كلمة جديدة، لكن لا أحد يستطيع قراءة القديمة.",
    claim: "كل رقم على شاشتك هو رقم قرّر الخادم أنه يحق لك رؤيته.",
    tagline: "مهارات اليوم، نجاح الغد",
    trades: {
      mechanics: "الميكانيك",
      it: "الإعلام الآلي والبرمجة",
      electrical: "الكهرباء",
      automotive: "السيارات",
      networking: "الشبكات",
    },
    principles: {
      permissionsTitle: "صلاحيات، لا أزرار مخفية",
      permissionsBody:
        "خمسة أدوار تتقاسم الشاشات نفسها. ما يختلف هو الأعمدة التي تصل — قائمة المكوِّن لا تحمل أي سعر، لأن السعر لا يُرسَل إليه أصلاً.",
      moneyTitle: "يقبضها واحد، ويصادق عليها آخر",
      moneyBody:
        "من يقبض المال لا يمكن أن يكون هو من يؤكد وصوله. القيود المصادق عليها نهائية؛ والتصحيح قيد جديد، لا تعديل.",
      trailTitle: "لا شيء يُحذف",
      trailBody:
        "الحسابات تُعطَّل، والتسجيلات تُلغى، والتقييمات تُخفى. أما أثر من فعل ماذا ومتى، فيبقى بعد كل ذلك.",
    },
  },

  empty: {
    errorTitle: "تعذّر تحميل هذه الصفحة",
    errorBody: "لم يعد الطلب. التحديث يحل المشكلة عادةً.",
    notFoundTitle: "هذه الصفحة غير موجودة",
    notFoundBody: "قد يكون الرابط قديماً، أو أن السجل أُزيل من نطاق رؤيتك.",
    notFound: "غير موجود",
    noAccessTitle: "{what} ليست ضمن دورك",
    noAccessSubject: "هذه الشاشة",
    noAccessBody:
      "لا شيء مخفي عنك هنا — السجلات وراء هذه الشاشة لا تُرسَل إلى حسابك إطلاقاً. إن كنت بحاجة إليها، يمكن للمالك منحك الصلاحية.",
    crashTitle: "لم تُحمَّل هذه الصفحة",
    crashBody:
      "توقفت بدل أن تعرض عليك شيئاً خاطئاً. لم يُحفظ أي شيء كنت تقوم به.",
    crashExplain:
      "حدث خلل في الطريق إلى هنا. لم يُحفظ أو يُغيَّر أي شيء كنت تقوم به — وإعادة المحاولة آمنة.",
    notFoundExplain:
      "لا يوجد هنا أي سجل يخصك. إما أنه غير موجود، وإما أن دورك لا يبلغه — والمنصة لا تفرّق بين الحالتين، عن قصد.",
    reference: "المرجع",
    nothing: "لا شيء هنا بعد.",
  },

  phrases: {
    seatsTaken: "{taken} مقعداً مشغولاً من {capacity}",
    seatsLeft: "{count} متبقياً",
    allTime: "{total} منذ البداية",
    onRecord: "{count} في السجل",
    draftFinished: "{draft} مسودة · {finished} منتهياً",
    countPayments: "{count} دفعة",
    assessmentsMarked: "{marked} تقييماً مصحَّحاً من {total}",
    studentsMarked: "{marked} متربصاً منقَّطاً من {total}",
    marksEntered: "{created} أُدخلت، و{updated} صُحِّحت.",
    correctedOne: "واحدة منها صُحِّحت بعد إدخالها أول مرة.",
    correctedMany: "{count} منها صُحِّحت بعد إدخالها أول مرة.",
    proofsAttached: "{count} مرفق",
    pendingApproval: "{id} بانتظار المصادقة.",
    paidOf: "{paid} مدفوعة من {total}",
    countsAgainstBalance: "{amount} صارت محتسبة على الرصيد.",
    closedInLedger: "{id} أُغلق. ويبقى القيد في السجل.",
    overSizeLimit:
      "{size} يتجاوز حد 10 ميغابايت. وصورة وصل عادةً أقل من ذلك بكثير.",
    rowsExported: "{count} سطراً.",
    starRating: "{count} نجوم",
    outOfFive: "{count} من 5",
    createdAs: "معرّف {name} هو {id}.",
    enrolledOn: "{name} صار مسجَّلاً في {course}.",
  },

  columns: {
    name: "الاسم",
    contact: "الاتصال",
    status: "الحالة",
    level: "المستوى",
    wilaya: "الولاية",
    runs: "الفترة",
    age: "السن",
    type: "النوع",
    mark: "النقطة",
    average: "المعدل",
    percent: "النسبة",
    action: "الفعل",
    onWhat: "على ماذا",
  },

  filters: {
    status: "الحالة",
    search: "بحث",
    role: "الدور",
    course: "التكوين",
    student: "المتربص",
    day: "اليوم",
    method: "الطريقة",
    who: "من",
    from: "من",
    to: "إلى",
    category: "الفئة",
    condition: "الحالة",
    location: "القاعة",
    month: "الشهر",
    year: "السنة",
  },

  dashboard: {
    title: "لوحة القيادة",
    morning: "صباح الخير",
    afternoon: "طاب يومك",
    evening: "مساء الخير",
    errorTitle: "تعذّر تحميل لوحة القيادة",
    errorBody: "لم تعد الأرقام من الخادم. التحديث يحل المشكلة عادةً.",
    blurbOwner: "هذا ما يجري اليوم في SM Academy.",
    blurbAdmin: "سير العمل في المؤسسة.",
    blurbReception: "يوم الاستقبال — تسجيلات ودفعات وقائمة المصادقة.",
    blurbProfessor: "ما هو قادم، وما ينتظر التصحيح.",
    blurbStudent: "تكويناتك ونقاطك ودفعاتك في مكان واحد.",
    attention: "يحتاج انتباهاً",
    attentionNote: "ينتظر شخصاً، لا موعداً.",
    awaitingApproval: "بانتظار المصادقة",
    awaitingApprovalNote: "مسجَّل، ولم يُصادق عليه بعد",
    unmarked: "تقييمات غير مصحَّحة",
    unmarkedNote: "لم تُدخَل أي نقطة",
    toModerate: "تقييمات للمراجعة",
    toModerateNote: "بانتظار قرار",
    money: "المال",
    moneyNote: "الدفعات المصادق عليها فقط. المال المعلَّق ليس إيراداً بعد.",
    collected: "المحصَّل هذا الشهر",
    collectedNote: "{total} منذ البداية",
    outstanding: "المتبقي للتحصيل",
    outstandingNote: "المتعاقد عليه ناقص المصادق عليه، على التسجيلات الجارية",
    teaching: "التكوين",
    activeCourses: "تكوينات نشطة",
    liveEnrollments: "تسجيلات جارية",
    myCourses: "تكويناتي",
    yourCourses: "تكويناتك",
    myStudents: "متربصوني",
    people: "الأشخاص",
    activeStudents: "متربصون نشطون",
    professors: "المكوِّنون",
    reception: "الاستقبال",
    administrators: "المسؤولون",
    today: "اليوم",
    enrollmentsToday: "تسجيلات اليوم",
    paymentsToday: "دفعات سُجِّلت اليوم",
    nextClass: "الحصة القادمة",
    openClass: "فتح الحصة",
    enrolledCount: "{count} مسجَّلاً",
    yourBalance: "رصيدك",
    stillToPay: "المتبقي للدفع",
    allPaidUp: "لا شيء مستحق. حسابك مسدَّد بالكامل.",
    settled: "مسدَّد",
    agreed: "المتفق عليه",
    paid: "المدفوع",
    remaining: "المتبقي",
    paidOfTotal: "{paid} مدفوعة من {total}",
    quickActions: "إجراءات سريعة",
    recordPayment: "تسجيل دفعة",
    enrolStudent: "تسجيل متربص",
    addPerson: "إضافة شخص",
    reviewPending: "مراجعة الدفعات المعلَّقة",
    enterMarks: "إدخال النقاط",
    runReport: "تشغيل تقرير",
    yourTimetable: "توقيتك",
    yourMarks: "نقاطك",
  },

  users: {
    title: "الأشخاص",
    lede: "الحسابات تُعطَّل ولا تُحذف أبداً — التسجيلات والدفعات والنقاط يجب أن تبقى منسوبة إلى شخص.",
    ledeSelf:
      "المعلومات التي نحتفظ بها عنك. اطلب من الاستقبال تصحيح أي خطأ فيها.",
    errorTitle: "تعذّر تحميل الأشخاص",
    searchPlaceholder: "الاسم أو المعرّف أو الهاتف",
    newPerson: "شخص جديد",
    newPersonLede:
      "لا يوجد تسجيل عمومي — كل حساب يُنشَأ هنا من طرف الموظفين، والأدوار التي يمكنك منحها محدودة بأدوارك أنت.",
    emptyTitle: "لا أحد يطابق هذه المعايير",
    emptyBody:
      "الحسابات خارج نطاقك لا تظهر في القائمة أصلاً — البحث يغطي فقط الأشخاص الذين يسمح لك دورك برؤيتهم.",
    lastSeen: "آخر ظهور",
    studentRecord: "ملف المتربص",
    professorRecord: "ملف المكوِّن",
    dateOfBirth: "تاريخ الميلاد",
    priorLevel: "المستوى السابق",
    emergencyContact: "جهة الاتصال للطوارئ",
    emergencyPhone: "هاتف الطوارئ",
    staffNotes: "ملاحظات داخلية",
    specialisation: "التخصص",
    hourlyRate: "الأجر بالساعة",
    qualifications: "الشهادات",
    hiredOn: "تاريخ التوظيف",
    address: "العنوان",
    wilaya: "الولاية",
    notGiven: "غير مذكور",
    notAssessed: "لم يُقيَّم",
    whoTheyAre: "الهوية",
    contactHint:
      "رقم الهاتف أو البريد الإلكتروني هو وسيلة الاتصال؛ أما المعرّف فهو وسيلة الدخول.",
    role: "الدور",
    chooseRole: "اختر دوراً",
    roleHint: "يحدد لوحة القيادة التي يصل إليها، والحقول المطبَّقة أدناه.",
    firstName: "الاسم",
    lastName: "اللقب",
    phone: "الهاتف",
    phoneHint: "يُحفظ بالصيغة الدولية. 0555 12 34 56 مقبول.",
    email: "البريد الإلكتروني",
    optionalLater: "كل ما يلي اختياري ويمكن استكماله لاحقاً.",
    dobHint: "يُستنتج العمر منه، ولا يُخزَّن.",
    createAccount: "إنشاء الحساب",
    accountCreated: "أُنشئ الحساب",
    roles: "الأدوار",
    rolesNote:
      "الدور مجموعة صلاحيات، لا مجرد تسمية. والدور الأساسي يحدد لوحة القيادة التي يصل إليها.",
    grantRole: "منح {role}",
    revokeRole: "سحب {role}",
    roleGranted: "مُنح {role}",
    roleRevoked: "سُحب {role}",
    accountStatus: "حالة الحساب",
    accountStatusNote:
      "الحسابات تُعطَّل ولا تُحذف أبداً — تسجيلاتها ودفعاتها ونقاطها تبقى منسوبة.",
    reason: "السبب",
    reasonPlaceholder: "غادر المؤسسة في نهاية الفصل.",
    reasonNote: "يُسجَّل في سجل التدقيق إلى جانب من قام بالتغيير.",
    reactivate: "إعادة التفعيل",
    suspend: "توقيف",
    deactivate: "تعطيل",
    cannotChangeStatus: "دورك لا يسمح بتغيير حالة هذا الحساب.",
    reactivated: "أُعيد تفعيل الحساب",
    reactivatedNote: "سيتمكن من الدخول مجدداً.",
    suspended: "أُوقف الحساب",
    deactivated: "عُطِّل الحساب",
    deactivatedNote:
      "يُخرَج من الجلسة عند طلبه التالي ولا يمكنه الدخول مجدداً. وتبقى سجلاته كما هي تماماً.",
    resetPasswordTitle: "إعادة تعيين كلمة المرور؟",
    resetPassword: "إعادة تعيين كلمة المرور",
    resetPasswordNote:
      "كل جلساته المفتوحة تتوقف فوراً، وتُعرَض عليك كلمة المرور الجديدة مرة واحدة.",
    newPasswordOnce: "سلِّمها له الآن. لن تُعرَض مرة أخرى.",
    primary: "أساسي",
  },

  courses: {
    title: "التكوينات",
    lede: "الكتالوج. كل تكوين يحمل سعره الخاص، وكل تسجيل يجمّد السعر الساري وقت إنشائه — لذا فتغيير سعر هنا لا يعيد كتابة فواتير الفصل الماضي أبداً.",
    errorTitle: "تعذّر تحميل التكوينات",
    searchPlaceholder: "العنوان أو المعرّف",
    emptyTitle: "لا تكوين يطابق هذه المعايير",
    emptyBody: "امسح عوامل التصفية لرؤية الكتالوج كاملاً.",
    taughtBy: "يؤطّرها",
    unassigned: "غير مسندة",
    price: "السعر",
    priceNote: "يُجمَّد على كل تسجيل لحظة إنشائه",
    seats: "المقاعد",
    uncapped: "بلا حد",
    weeklySchedule: "التوقيت الأسبوعي",
    weeklyScheduleNote: "نمط متكرر، لا جدول حصص مؤرَّخة.",
    fullTimetable: "التوقيت الكامل",
    assessments: "التقييمات",
    assessmentsNote: "لكل واحد معامل، أي نصيبه من المعدل.",
    noAssessments: "لا تقييمات بعد",
    noAssessmentsBody:
      "تظهر النقاط والمعدلات هنا بمجرد وجود تقييم على هذا التكوين.",
    onlyPublished: "التقييمات المنشورة وحدها تُظهر نقطة.",
    yourEnrollment: "تسجيلك",
    gradebook: "كشف النقاط",
    yourMarks: "نقاطك",
    published: "منشور",
    notPublished: "غير منشور",
  },

  enrollments: {
    title: "التسجيلات",
    titleSelf: "تسجيلاتك",
    lede: "سطر واحد لكل متربص في كل تكوين، بالسعر المتفق عليه حينها. الدفعات والنقاط تتفرع عنها، ولهذا تُلغى بدل أن تُحذف.",
    errorTitle: "تعذّر تحميل التسجيلات",
    emptyTitle: "لا تسجيل يطابق هذه المعايير",
    emptyBody: "التسجيل هو متربص واحد في تكوين واحد. امسح المعايير لرؤيتها كلها.",
    agreedPrice: "السعر المتفق عليه",
    enrolled: "سُجِّل في",
    enrolOne: "تسجيل متربص",
    enrolLede:
      "متربص واحد، تكوين واحد. وكل ما عدا ذلك — الدفعات والنقاط والتقييم — يتفرع عن التسجيل الذي يُنشأ هنا.",
    detailTitle: "التسجيل",
    detailLede: "متربص واحد، تكوين واحد — وكل ما يتصل بهذا الاقتران.",
    course: "التكوين",
    profile: "الملف",
    priceAgreed: "السعر المتفق عليه عند التسجيل",
    student: "المتربص",
    chooseStudent: "اختر متربصاً",
    chooseStudentHint: "حسابات المتربصين النشطة فقط.",
    chooseCourse: "اختر تكويناً",
    chooseCourseHint: "التكوينات في حالة مسودة أو نشطة تقبل التسجيل.",
    notes: "ملاحظات",
    notesPlaceholder: "الدفع على ثلاثة أقساط؛ أخ لـ STU-000004.",
    notesHint: "يُشعَر المعني، ويبدأ التسجيل نشطاً.",
    whatWillBeRecorded: "ما سيُسجَّل",
    courseRuns: "يجري التكوين",
    priceFrozen: "السعر، مجمَّد عند التسجيل",
    submit: "تسجيل المتربص",
    done: "تم التسجيل",
    balance: "الرصيد",
    balanceNote: "يُحسَب من سطور الدفع عند كل قراءة، ولا يُخزَّن أبداً.",
    frozenAtEnrollment: "مجمَّد عند التسجيل",
    approvedPayments: "الدفعات المصادق عليها",
    awaitingApproval: "بانتظار المصادقة",
    notCountedAsPaid: "لا تُحتسب مدفوعة",
    remaining: "المتبقي",
    stillOwed: "ما يزال مستحقاً",
    outstanding: "مستحق",
    payments: "الدفعات",
    paymentsNote: "كل قيد يُسجَّل أولاً ثم يصادق عليه شخص آخر.",
    paymentsFor: "دفعات هذا التسجيل",
    noPayments: "لم يُسجَّل شيء على هذا التسجيل بعد",
    noPaymentsBody:
      "نقداً في المكتب، أو تحويلاً، أو صكاً — كلها تُسجَّل هنا ثم يُصادق عليها.",
    reference: "المرجع",
  },

  grades: {
    title: "النقاط",
    lede: "تُحسب المعدلات من النقاط الخام في كل مرة تُطلب فيها، ولا تُخزَّن. غيِّر معامل تقييم واحد وتتحرك كل المعدلات معه.",
    scopeNote: "كشف النقاط محصور في التكوينات المسندة إليك.",
    noCourses: "لا تكوينات مسندة إليك",
    noCoursesBody: "يظهر كشف النقاط هنا بمجرد إسناد تكوين إليك.",
    chooseCourse: "اختر تكويناً",
    chooseCourseBody: "اختر واحداً أعلاه لرؤية كشف نقاطه وأوراق التنقيط.",
    markSheets: "أوراق التنقيط",
    markSheetsNote: "افتح واحدة لإدخال النقاط أو تصحيحها.",
    noAssessments: "لا تقييمات على هذا التكوين",
    noAssessmentsBody:
      "النقاط تُدخَل على تقييم، فلا بد أن يوجد تقييم قبل أن توجد الورقة.",
    gradebook: "كشف النقاط",
    nobodyEnrolled: "لم يُسجَّل أحد في هذا التكوين بعد",
    nobodyEnrolledBody:
      "يمتلئ كشف النقاط مع تسجيل المتربصين وتصحيح التقييمات.",
    notMarkedYet: "لم يُنقَّط بعد",
    yourMarks: "نقاطك",
    yourMarksLede:
      "النتائج المنشورة فقط. تظهر النقطة هنا حين ينشر مكوِّنك التقييم الذي تنتمي إليه.",
    noMarks: "لا نقاط منشورة بعد",
    noMarksBody:
      "ينشر مكوِّنك التقييم متى صُحِّح القسم كله. لا شيء مخفي عنك هنا — لا يوجد شيء بعد، ببساطة.",
    corrected: "مصحَّحة",
    assessment: "التقييم",
    recorded: "سُجِّلت في",
    markSheet: "ورقة التنقيط",
    outOf: "من",
    weight: "المعامل",
    weightNote: "نصيبه من معدل التكوين",
    marked: "المنقَّطون",
    heldOn: "أُجري في",
    published: "منشور",
    notPublished: "غير منشور",
    student: "المتربص",
    comment: "تعليق",
    history: "السجل",
    notMarked: "غير منقَّط",
    saveSheet: "حفظ الورقة",
    enterMoves: "زر الإدخال أو السهم الأسفل ينتقل إلى المتربص التالي.",
    atomicNote: "تُحفظ الورقة كوحدة واحدة: إما أن تُسجَّل كل النقاط أو لا شيء.",
    sheetSaved: "حُفظت الورقة",
    publishTitle: "نشر هذه النقاط؟",
    publishAction: "نشر النقاط",
    publishBody:
      "يُشعَر كل متربص له نقطة. ولا يمكن التراجع عن ذلك — النقطة الخاطئة تُصحَّح ولا تُخفى.",
    notPublishedNote:
      "لا يرى المتربصون هذه النقاط بعد. النشر يُشعِر كل من له نقطة.",
    publishedNote: "كل متربص في القائمة له نقطة.",
    marksPublished: "نُشرت النقاط",
    marksPublishedNote: "أُشعِر كل من له نقطة.",
  },

  payments: {
    title: "الدفعات",
    lede: "كل قيد يُسجَّل، ثم يصادق عليه شخص آخر. لا شيء هنا يُعدَّل أو يُحذف — الخطأ قبل المصادقة يُلغى، والخطأ بعدها يُصحَّح بقيد جديد.",
    errorTitle: "تعذّر تحميل الدفعات",
    emptyTitle: "لا دفعة تطابق هذه المعايير",
    emptyBody: "امسح المعايير لرؤية كل القيود.",
    reference: "المرجع",
    noReferenceNote: "النقد المقبوض في المكتب لا يحمل مرجعاً عادةً.",
    recordedDecided: "مسجَّل / تقرَّر",
    amount: "المبلغ",
    student: "المتربص",
    course: "التكوين",
    currency: "العملة",
    method: "الطريقة",
    paidOn: "دُفعت في",
    recordTitle: "تسجيل دفعة",
    recordLede:
      "مال وصل، منسوب إلى التسجيل الذي يخصه. كل قيد يبدأ معلَّقاً ويصادق عليه شخص آخر — ولا يمكنك المصادقة على قيد سجّلته بنفسك.",
    enrollment: "التسجيل",
    chooseEnrollment: "اختر متربصاً وتكويناً",
    chooseEnrollmentHint:
      "التسجيلات النشطة فقط. المال على تسجيل منسحب يتطلب تسجيلاً جارياً أولاً.",
    amountHint: "المبلغ المسلَّم، بوحدات كاملة أو بالسنتيمات.",
    amountPlaceholder: "20000",
    paidOnHint: "اليوم الذي وصل فيه المال، لا تاريخ اليوم إن اختلفا.",
    methodHint: "كيف تم الدفع",
    notes: "ملاحظات",
    notesPlaceholder: "القسط الثاني؛ وصل رقم 41.",
    against: "على",
    loadingBalance: "جارٍ تحميل الرصيد…",
    agreed: "المتفق عليه",
    paid: "المدفوع",
    pending: "معلَّق",
    remaining: "المتبقي",
    attachLater: "يُرفق وصل البنك في صفحة الدفعة نفسها، بعد إنشائها.",
    submit: "تسجيل الدفعة",
    recorded: "سُجِّلت الدفعة",
    pendingNoticeSelf:
      "سيبقى هذا القيد معلَّقاً. ولن تستطيع المصادقة عليه بنفسك — من يسجّل دفعة لا يمكن أن يكون هو من يؤكد وصولها.",
    pendingNotice:
      "سيبقى هذا القيد معلَّقاً حتى يؤكده شخص له صلاحية المصادقة. الاستقبال يسجّل المال ولا يصادق عليه.",
    amountInvalid: "أدخل مبلغاً، مثل 20000 أو 20000.50.",
    amountTooSmall: "يجب أن يكون المبلغ أكبر من الصفر.",
    details: "التفاصيل",
    history: "السجل",
    proof: "الإثبات",
    decision: "القرار",
    decisionNote: "يسجّله شخص، ويؤكده آخر.",
    notRecorder: "ليس من سجّلها",
    selfApproveBlocked: "أنت من سجّل هذه الدفعة. يجب أن يصادق عليها شخص آخر.",
    statePending: "مسجَّلة، ولم يُصادق عليها بعد. ولا تُحتسب مدفوعة.",
    stateApproved: "مصادق عليها ومحتسبة على الرصيد.",
    stateRejected: "مرفوضة. لم يُحتسب شيء.",
    stateCancelled: "أُلغيت قبل اتخاذ أي قرار.",
    reasonForRejection: "سبب الرفض",
    approveTitle: "المصادقة على هذه الدفعة؟",
    approveAction: "المصادقة على الدفعة",
    approveBody: "هذا يحتسب المال على الرصيد ولا يمكن التراجع عنه.",
    approve: "مصادقة",
    rejectTitle: "رفض هذه الدفعة؟",
    rejectAction: "رفض الدفعة",
    rejectBody: "يبقى القيد في السجل مع السبب مرفقاً به.",
    reject: "رفض",
    rejectWhy: "ما سبب هذا الرفض؟",
    rejectWhyHint: "من رُفض طلبه يجب أن يكون بالإمكان إخباره بالسبب.",
    cancelTitle: "إلغاء هذا القيد؟",
    cancelAction: "إلغاء القيد",
    cancelBody: "لقيد ما كان ينبغي إنشاؤه. يبقى في السجل، مغلقاً.",
    cancelWhy: "ما سبب هذا الإلغاء؟",
    cancelWhyPlaceholder: "سُجِّل على التسجيل الخطأ.",
    reasonShown: "يُسجَّل مع الدفعة ويظهر لكل من يطّلع عليها.",
    approved: "صودق على الدفعة",
    rejected: "رُفضت الدفعة",
    cancelled: "أُلغي القيد",
    noProof: "لا إثبات مرفق.",
    proofAttached: "أُرفق الإثبات",
    proofScanNote: "يُفحص قبل أن يتمكن أحد من فتحه.",
    scanning: "ما يزال قيد الفحص. لا يُسلَّم ملف قبل فحصه.",
    scanned: "مفحوص",
    uploading: "جارٍ الرفع…",
    attachProof: "إرفاق إثبات",
    downloadFailed: "تعذّر تحضير التنزيل.",
    storageRefused: "رفضت خدمة التخزين هذا الملف.",
    uploadIncomplete: "لم يكتمل الرفع.",
  },

  reviews: {
    title: "التقييمات",
    lede: "يكتبها متربصون أنهوا تكويناً. لا شيء يُحذف — الإخفاء أو الرفض يبقي السطر والقرار وصاحبه.",
    ledeProfessor:
      "ما قاله المتربصون عن التكوينات التي يمكنك رؤيتها. التقييمات المصادق عليها فقط، ودون اسم الكاتب أبداً بالنسبة للمكوِّن.",
    errorTitle: "تعذّر تحميل التقييمات",
    byCourse: "حسب التكوين",
    byCourseNote:
      "التقييمات المصادق عليها فقط، ويُحسب عند القراءة. المعدل المخزَّن لا يمكن إعادة اشتقاقه بعد إخفاء تقييم.",
    awaitingModeration: "بانتظار المراجعة",
    nothingToModerate: "لا شيء للمراجعة",
    caughtUp:
      "أنت على اطلاع بكل شيء. تصل تقييمات جديدة كلما أنهى متربصون تكويناتهم.",
    emptyTitle: "لا تقييمات هنا بعد",
    noComment: "لم يُترك تعليق.",
    anonymous: "مجهول",
    replyFromInstitute: "رد المؤسسة",
    publicReply: "رد علني",
    publicReplyNote: "يُنشر مع التقييم إن صادقت عليه.",
    moderate: "مراجعة",
    changeDecision: "تغيير القرار",
    approve: "مصادقة",
    reject: "رفض",
    rejectTitle: "رفض هذا التقييم؟",
    rejectAction: "رفض التقييم",
    rejectBody: "يبقى في السجل مع قرارك، ولا يظهر علناً أبداً.",
    approved: "صودق على التقييم",
    hidden: "أُخفي التقييم",
    rejected: "رُفض التقييم",
    keptNote: "السطر والقرار وصاحبه، كلها محفوظة.",
    writeTitle: "قيِّم تكويناً",
    writeNote: "لن يعرف مكوِّنك أبداً من كتبه.",
    rating: "التنقيط",
    comment: "تعليق",
    commentPlaceholder: "ما كان جيداً، وما يمكن تحسينه.",
    submit: "إرسال التقييم",
    submitted: "أُرسل التقييم",
  },

  schedules: {
    title: "التوقيت",
    lede: "نمط أسبوعي متكرر، لا جدول حصص مؤرَّخة. كل حصة تتكرر أسبوعياً بين تاريخَي سريانها.",
    errorTitle: "تعذّر تحميل التوقيت",
    emptyTitle: "لا حصص مبرمجة",
    emptyBody: "سيظهر توقيتك الأسبوعي هنا بمجرد إسناد تكوين إليك.",
    session: "حصة",
  },

  reports: {
    title: "التقارير",
    lede: "كل رقم يُقرأ من السطور عند كل طلب — لا شيء يُخزَّن مؤقتاً ولا شيء يُحفظ، فتتطابق المجاميع مع السجل بحكم البناء نفسه.",
    noneForRole: "لا تقارير تناسب دورك",
    noneForRoleBody:
      "قراءة تقرير صلاحية قائمة بذاتها، تُمنح بمعزل عن الشاشات التي تأتي منها الأرقام.",
    errorTitle: "تعذّر تشغيل هذا التقرير",
    errorBody:
      "لم يعد الاستعلام. تضييق المدة الزمنية وإعادة المحاولة يحل المشكلة عادةً.",
    totals: "المجاميع",
    rows: "السطور",
    emptyTitle: "لا شيء يطابق هذه المعايير",
    emptyBody: "وسّع المدة الزمنية، أو امسح التكوين، لرؤية سطور أكثر.",
    enrollmentsTitle: "التسجيلات",
    enrollmentsNote: "العدد لكل تكوين، حسب الحالة. لا مبالغ فيه إطلاقاً.",
    revenueTitle: "الإيرادات",
    revenueNote:
      "المال المحصَّل فعلاً، حسب التكوين. الدفعات المصادق عليها فقط.",
    outstandingTitle: "المتبقي للتحصيل",
    outstandingNote: "ما يزال كل تسجيل جارٍ مديناً به.",
    unsettledOnly: "غير المسدَّدة فقط",
    export: "تصدير",
    exportNote: "ملف CSV يضم السطور أعلاه بالضبط، يُبنى في الخلفية.",
    exportBuilding: "جارٍ بناء الملف…",
    exportDownload: "تنزيل",
    exportNothingQueued: "لا شيء في الانتظار بعد.",
    exportPrivate: "خاص",
    exportTooLong: "التصدير يستغرق وقتاً أطول من المتوقع. عُد لاحقاً.",
    exportReady: "التصدير جاهز",
    exportLost: "فُقد أثر التصدير. أعد التحميل لمعرفة حالته.",
    exportAgain: "تصدير مرة أخرى",
    exportCsv: "تصدير CSV",
    exportFailed: "فشل التصدير.",
  },

  audit: {
    title: "سجل التدقيق",
    lede: "الإضافة فقط، تفرضها قاعدة البيانات لا مجرد العرف — لا توجد أي نقطة وصول تعدّل سطراً أو تحذفه في أي إصدار، والأفعال الأجدر بالتسجيل هنا هي بالضبط تلك التي قد يرغب أحدهم في محوها.",
    errorTitle: "تعذّرت قراءة السجل",
    emptyTitle: "لا شيء مسجَّل لهذه المعايير",
    emptyBody:
      "السجل يضم كل فعل ذي أثر. فإن كان فارغاً، فلأن لا شيء منها يطابق — لا لأن شيئاً لم يحدث.",
    loadMore: "تحميل المزيد",
    endOfTrail: "هذا هو الأثر كله.",
    loadMoreFailed: "تعذّر تحميل المزيد.",
    actions: {
      loginFailed: "محاولة دخول فاشلة",
      userCreated: "أُنشئ حساب",
      userUpdated: "عُدِّل حساب",
      userStatusChanged: "تغيّرت حالة حساب",
      passwordReset: "أُعيد تعيين كلمة مرور",
      roleGranted: "مُنح دور",
      roleRevoked: "سُحب دور",
      studentEnrolled: "سُجِّل متربص",
      markChanged: "عُدِّلت نقطة",
      marksPublished: "نُشرت نقاط",
      paymentRecorded: "سُجِّلت دفعة",
      paymentApproved: "صودق على دفعة",
      paymentRejected: "رُفضت دفعة",
      proofDownloaded: "نُزِّل إثبات",
      reviewModerated: "روجع تقييم",
      reportExported: "صُدِّر تقرير",
      exportDownloaded: "نُزِّل تصدير",
    },
    subjects: {
      enrollment: "تسجيل",
      reportExport: "تصدير",
      person: "شخص",
      payment: "دفعة",
      course: "تكوين",
      review: "تقييم",
    },
  },

  notifications: {
    title: "الإشعارات",
    lede: "موجَّهة إليك وحدك — تسجيل باسمك، أو نقطة نُشرت، أو دفعة تقرَّر بشأنها.",
    errorTitle: "تعذّر تحميل الإشعارات",
    unreadOnly: "غير المقروءة",
    markAllRead: "تعليم الكل كمقروء",
    allMarkedRead: "عُلِّم الكل كمقروء",
    nothingUnread: "لا شيء غير مقروء",
    caughtUp: "أنت على اطلاع بكل شيء.",
    all: "الكل",
    emptyTitle: "لا إشعارات بعد",
    emptyBody:
      "ستُخبَر بما يعنيك — تسجيل، أو نقطة نُشرت، أو دفعة تقرَّر بشأنها.",
  },

  account: {
    title: "حسابك",
    lede: "ما نحتفظ به عنك، وما يسمح لك دورك بالوصول إليه.",
    fullRecord: "الملف الكامل",
    lastSignedIn: "آخر دخول",
    permissionsTitle: "ما يسمح به دورك",
    permissionsNote:
      "يُمنح بالصلاحية، لا بالمسمى الوظيفي. والخادم يتحقق من كل واحدة منها عند كل طلب.",
    password: "كلمة المرور",
    passwordNote:
      "تُغيَّر هنا، بيدك أنت. ولا أحد يستطيع قراءة الحالية — فهي لم تُخزَّن قط بصيغة قابلة للقراءة.",
    current: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    newPasswordHint:
      "الطول خير من التعقيد. عبارة تتذكرها أقوى من كلمة مليئة بالرموز.",
    repeat: "أعد كتابة كلمة المرور الجديدة",
    submit: "تغيير كلمة المرور",
    changed: "تغيّرت كلمة المرور",
    changedNote: "استعمل الجديدة في دخولك القادم.",
    mismatch: "الكلمتان غير متطابقتين.",
    correctionNote:
      "هل هناك خطأ هنا؟ اطلب من الاستقبال تصحيحه — تعديلات ملف أي شخص تتم في مكان واحد، حيث تُسجَّل.",
    sessionNote:
      "تغيير كلمة المرور لا يُخرجك من هذا المتصفح. وإن كنت تظن أن شخصاً آخر يستعمل حسابك، فأبلغ مسؤولاً.",
  },


  // ----------------------------------------------------------- logistics --

  // --------------------------------------------------------------- print --

  // ---------------------------------------------------------- attendance --

  // ------------------------------------------------------------ settings --
  settings: {
    title: "الإعدادات",
    lede: "بيانات المؤسسة. تفتتح كل مستند مطبوع، فما هنا هو ما يظهر على وصل يُسلَّم لوليّ.",
    errorTitle: "تعذّر تحميل الإعدادات",
    identity: "الهوية",
    identityLede: "الاسم على اللافتة، والاسم القانوني إن اختلف.",
    contact: "العنوان والاتصال",
    contactLede: "تُطبع تحت الاسم في كل تقرير. وما يُترك فارغًا يُحذف من الصفحة ببساطة.",
    documents: "المستندات المطبوعة",
    documentsLede: "ما يظهر أسفل كل صفحة، بجانب رقمها.",
    name: "اسم المؤسسة",
    legalName: "الاسم القانوني",
    addressLine: "العنوان",
    city: "البلدية",
    wilaya: "الولاية",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    website: "الموقع الإلكتروني",
    registrationNumber: "رقم التسجيل",
    tagline: "الشعار",
    printFooter: "تذييل الصفحة",
    saved: "حُفظت الإعدادات",
    readOnly: "يدير هذه البيانات المالك. يمكنك رؤية ما يظهر على المستندات المطبوعة دون تغييره.",
    logoNote: "الشعار هو العمل الفني الرسمي داخل التطبيق ولا يُعدّل من هنا — فنسخة ثانية تُرفع عبر نموذج هي الطريق إلى مؤسسة بشعارين دون جواب عن أيهما المعتمد.",
    previewTitle: "ترويسة المستندات",
  },
  attendance: {
    title: "الحضور",
    lede: "ورقة واحدة لكل قسم في كل يوم. الورقة التي لم يسجّلها أحد فارغة، وهذا غير أن يكون الجميع غائبين.",
    errorTitle: "تعذّر تحميل الحضور",
    emptyTitle: "لا أوراق حضور بعد",
    emptyBody: "افتح واحدة لقسم وتاريخ، فتظهر القائمة كاملة جاهزة للتسجيل.",
    openRegister: "فتح ورقة حضور",
    openRegisterLede: "اختر القسم واليوم. وإن كان أحد قد فتحها من قبل، ستُنقل إلى ورقته بدل إنشاء ثانية.",
    takeRegister: "تسجيل الحضور",
    saveRegister: "حفظ الورقة",
    saved: "حُفظت الورقة",
    savedDetail: "{created} مسجّلًا، {updated} مصحّحًا.",
    heldOn: "التاريخ",
    classLabel: "القسم",
    topic: "الموضوع",
    topicHint: "ما جرى تناوله، إن كان يستحق التسجيل.",
    room: "القاعة",
    marked: "مسجّلون",
    roster: "المسجّلون",
    present: "حاضرون",
    absent: "غائبون",
    late: "متأخرون",
    rate: "النسبة",
    minutesLate: "دقائق التأخر",
    note: "ملاحظة",
    markAllPresent: "الجميع حاضر",
    clearAll: "مسح الكل",
    corrected: "مصحّح",
    correctedNote: "غُيّر هذا التسجيل بعد إدخاله أول مرة.",
    summary: "حصيلة الحضور",
    summaryLede: "النسب خلال الفترة، لكل متربص. التأخر يُحتسب حضورًا.",
    noRate: "لم يُسجَّل حضور",
    notOnRoster: "لا أحد مسجّل في هذا القسم بعد.",
    readOnly: "يمكنك الاطلاع على الحضور وطباعته. أما تسجيله فهو لأستاذ القسم.",
    printRegister: "طباعة ورقة الحضور",
    printSummary: "طباعة تقرير الحضور",
    blankSheet: "الورقة التي لم تُسجَّل تُطبع فارغة، جاهزة للملء باليد.",
  },
  print: {
    print: "طباعة",
    printThis: "طباعة هذه القائمة",
    savePdf: "حفظ بصيغة PDF",
    preview: "معاينة الطباعة",
    generated: "أُنشئ في",
    pageOf: "صفحة {page} من {total}",
    dialogHint: "تُفتح نافذة الطباعة من تلقائها. وخيار «حفظ بصيغة PDF» في متصفحك ينتج المستند نفسه كملف.",
    nothingToPrint: "لا شيء للطباعة في هذه القائمة.",
    truncated: "يعرض هذا المستند أول 2000 سجل من قائمة أكبر. ضيّق المرشّحات لطباعة البقية.",
    filteredNotice: "هذه قائمة مُرشَّحة، وليست القائمة كاملة.",
    openInNewTab: "يفتح ورقة A4 قابلة للطباعة في تبويب جديد.",
    studentList: "قائمة المتربصين",
    staffList: "قائمة الموظفين",
    studentProfile: "بطاقة المتربص",
    courseList: "قائمة التكوينات",
    classList: "قائمة القسم",
    enrollmentList: "قائمة التسجيلات",
    scheduleTitle: "جدول الحصص",
    incomeReport: "تقرير المداخيل",
    receiptTitle: "وصل دفع",
    financialSummary: "الحصيلة المالية",
    attendanceRegister: "ورقة الحضور",
    attendanceReport: "تقرير الحضور",
    managementReport: "تقرير التسيير",
    gradebookTitle: "كشف النقاط",
    totalStudents: "مجموع المتربصين",
    totalStaff: "مجموع الموظفين",
    totalCourses: "مجموع التكوينات",
    totalEnrollments: "مجموع التسجيلات",
    totalRecords: "مجموع السجلات",
    totalIncome: "مجموع المداخيل",
    totalExpenses: "مجموع المصاريف",
    netBalance: "الرصيد الصافي",
    outstanding: "المتبقي",
    attendanceRate: "نسبة الحضور",
    preparedBy: "أعدّه",
    signature: "التوقيع",
    receivedBy: "استلمه",
    period: "الفترة",
    allTime: "منذ البداية",
    receiptNumber: "رقم الوصل",
    amountPaid: "المبلغ المدفوع",
    remainingBalance: "الرصيد المتبقي",
    payer: "وردت من",
    forCourse: "عن",
    pendingNotice: "يوثّق هذا الوصل دفعة ما تزال بانتظار الموافقة.",
    incomeByCourse: "المداخيل حسب التكوين",
    expensesByCategory: "المصاريف حسب الفئة",
    monthByMonth: "شهرًا بشهر",
    income: "المداخيل",
    expenditure: "المصاريف",
    net: "الصافي",
    people: "الأشخاص",
    teaching: "التكوين",
    money: "المال",
    inventory: "الجرد",
    newRegistrations: "تسجيلات جديدة",
    activeStudents: "متربصون نشطون",
    activeCourses: "تكوينات جارية",
    liveEnrollments: "تسجيلات جارية",
    registersTaken: "أوراق حضور مسجّلة",
    pendingPayments: "دفعات معلّقة",
    itemsNeedingRepair: "عناصر تحتاج إصلاحًا",
    itemsDamaged: "عناصر تالفة",
    itemsMissing: "عناصر مفقودة",
    inventoryLines: "أسطر الجرد",
    inventoryUnits: "مجموع العناصر",
    registered: "تاريخ التسجيل",
    date: "التاريخ",
    time: "التوقيت",
    entries: "القيود",
    balance: "الرصيد",
    notes: "ملاحظات",
    status: "الحالة",
    summary: "الحصيلة",
  },
  logistics: {
    title: "اللوجستيك",
    lede: "ما تملكه الأكاديمية، وما يكلّفه إبقاء الأبواب مفتوحة. الجرد والمصاريف الشهرية في مكان واحد.",
    inventory: "الجرد",
    expensesTab: "المصاريف",
    historyTab: "السجل الشهري",
    setupTab: "الفئات والقاعات",
    readOnly: "يمكنك الاطلاع على كل شيء هنا وطباعته. أما الإضافة والتعديل والحذف فهي للمالك أو المسؤول.",
    errorTitle: "تعذّر تحميل الجرد",
    emptyTitle: "لا شيء في الجرد بعد",
    emptyBody: "سجّل الكراسي والطاولات والآلات والعتاد الذي تملكه الأكاديمية. كل عنصر يمكن عدّه وتحديد مكانه وطباعته.",
    addItem: "إضافة عنصر",
    editItem: "تعديل العنصر",
    itemLede: "سطر واحد من الجرد. الأشياء المتطابقة تُعدّ معًا؛ وكل ما يحمل رقمًا تسلسليًا له سطره الخاص.",
    addItemLede: "تُدار الفئات والقاعات من تبويب الإعداد، فنوع عتاد جديد لا يحتاج مطوّرًا أبدًا.",
    name: "اسم العنصر",
    category: "الفئة",
    quantity: "الكمية",
    condition: "الحالة",
    status: "الوضع",
    location: "المكان / القاعة",
    purchaseDate: "تاريخ الشراء",
    purchasePrice: "سعر الشراء",
    serial: "الرقم التسلسلي",
    notes: "ملاحظات",
    lastUpdated: "آخر تحديث",
    added: "أُضيف",
    reference: "الوصل أو المرجع",
    method: "طريقة الدفع",
    amount: "المبلغ",
    spentOn: "تاريخ الدفع",
    accountingMonth: "الشهر المحاسبي",
    description: "الوصف",
    quantityHint: "كم عددًا من هذا العنصر بالضبط. لا يكون سالبًا أبدًا.",
    serialHint: "للآلات. لا يمكن أن يتشارك عنصران رقمًا تسلسليًا واحدًا.",
    priceHint: "ما كلّفه، إن كان معروفًا. اتركه فارغًا إن لم يكن كذلك.",
    accountingMonthHint: "الشهر الذي تنتمي إليه. يتبع تاريخ الدفع — غيّره حين تُدفع فاتورة فيفري في مارس.",
    noCategories: "لا توجد فئات بعد. أضف واحدة من تبويب الإعداد أولًا.",
    noLocations: "لا توجد قاعات مسجّلة. يمكن تصنيف العنصر دون قاعة.",
    totalItems: "أسطر الجرد",
    totalUnits: "مجموع العناصر",
    totalUnitsNote: "بحساب الكميات لا الأسطر.",
    needingRepair: "يحتاج إصلاحًا",
    damaged: "تالف",
    missing: "مفقود",
    underRepair: "قيد الإصلاح",
    available: "متاح",
    inUse: "قيد الاستعمال",
    categoriesCount: "الفئات",
    roomsCount: "القاعات",
    byCategory: "حسب الفئة",
    byLocation: "حسب القاعة",
    byCondition: "حسب الحالة",
    recentlyAdded: "أُضيف مؤخرًا",
    lines: "أسطر",
    expensesTitle: "المصاريف الشهرية",
    expensesLede: "ما أنفقه المعهد، مصنّفًا حسب الشهر الذي ينتمي إليه لا حسب يوم دفعه.",
    expensesErrorTitle: "تعذّر تحميل المصاريف",
    expensesEmptyTitle: "لا شيء مسجّل لهذا الشهر",
    expensesEmptyBody: "الكهرباء والماء والإنترنت والإصلاحات والتنظيف — كل ما دفعه المعهد مكانه هنا.",
    addExpense: "إضافة مصروف",
    editExpense: "تعديل المصروف",
    addExpenseLede: "شيء واحد دفعه المعهد. مجموع الشهر يحسبه الخادم، لا هذه الشاشة.",
    monthTotal: "هذا الشهر",
    previousMonth: "الشهر السابق",
    yearTotal: "منذ بداية السنة",
    entriesThisMonth: "القيود هذا الشهر",
    upOn: "{amount} أكثر من {month}",
    downOn: "{amount} أقل من {month}",
    sameAs: "مثل {month}",
    firstMonth: "لم يُسجَّل شيء في {month}.",
    breakdown: "حسب الفئة",
    monthlyTotals: "شهرًا بشهر",
    historyTitle: "السجل الشهري",
    historyLede: "كل شهر فيه تسجيل، من الأحدث إلى الأقدم. افتح شهرًا لقراءة قيوده.",
    historyEmptyTitle: "لا أشهر مسجّلة بعد",
    historyEmptyBody: "ما إن تُسجَّل المصاريف حتى يظهر كل شهر هنا بمجموعه وبفئته الأثقل.",
    monthColumn: "الشهر",
    totalColumn: "مجموع المصاريف",
    mainCategory: "الفئة الرئيسية",
    entries: "القيود",
    viewMonth: "عرض",
    setupTitle: "الفئات والقاعات",
    setupLede: "التسميات التي يصنّف بها هذا القسم. إنها بيانات لا شيفرة — نوع عتاد جديد يُضاف من هنا.",
    itemCategories: "فئات العناصر",
    expenseCategories: "فئات المصاريف",
    rooms: "القاعات والمخازن",
    addCategory: "إضافة فئة",
    addRoom: "إضافة قاعة",
    newCategoryPlaceholder: "طابعات ثلاثية الأبعاد",
    newRoomPlaceholder: "القاعة 3",
    retire: "سحب",
    restore: "استرجاع",
    retired: "مسحوب",
    retiredNote: "التسمية المسحوبة تختفي من القوائم. وكل ما صُنّف تحتها من قبل يحتفظ باسمه.",
    filedUnder: "{count} مصنّف هنا",
    nothingFiled: "لا شيء مصنّف هنا بعد",
    print: "طباعة",
    printInventory: "طباعة قائمة اللوجستيك",
    printExpenses: "طباعة مصاريف الشهر",
    printNow: "طباعة",
    printHint: "يفتح ورقة A4 قابلة للطباعة في تبويب جديد.",
    printingDialog: "تُفتح نافذة الطباعة من تلقائها. أغلق هذا التبويب عند الانتهاء.",
    documentTitle: "جرد اللوجستيك",
    expensesDocumentTitle: "المصاريف الشهرية",
    printedOn: "طُبع في",
    printedTotalItems: "مجموع العناصر",
    printedTotalLines: "أسطر الجرد",
    printedTotalExpenses: "مجموع مصاريف الشهر",
    filteredNotice: "هذه قائمة مُرشَّحة، وليست الجرد كاملًا.",
    nothingToPrint: "لا شيء للطباعة في هذه القائمة.",
    deleteItem: "حذف العنصر",
    deleteItemBody: "{name} يغادر الجرد وكل المجاميع فورًا. ويبقى أثره في سجل التدقيق.",
    deleteExpense: "حذف المصروف",
    deleteExpenseBody: "{name} يغادر مجموع هذا الشهر فورًا. ويبقى أثره في سجل التدقيق.",
    itemDeleted: "أُزيل العنصر",
    expenseDeleted: "أُزيل المصروف",
    itemAdded: "أُضيف العنصر",
    itemSaved: "حُفظ العنصر",
    expenseAdded: "سُجّل المصروف",
    expenseSaved: "حُفظ المصروف",
    categoryAdded: "أُضيفت الفئة",
    roomAdded: "أُضيفت القاعة",
    sectionItem: "العنصر",
    sectionPurchase: "الشراء والتعريف",
    sectionExpense: "المصروف",
    sectionFiling: "التصنيف",
  },
  perms: {
    groupUsers: "الأشخاص والوصول",
    groupCatalogue: "الكتالوج",
    groupEnrollment: "التسجيل",
    groupMoney: "المال",
    groupEngagement: "العلاقة",
    groupOversight: "الرقابة",
    "user.view": "رؤية الأشخاص",
    "user.create": "إنشاء حسابات",
    "user.update": "تعديل الأشخاص",
    "user.deactivate": "تعطيل حسابات",
    "user.reset_password": "إعادة تعيين كلمات المرور",
    "user.assign_role": "إسناد الأدوار",
    "role.manage": "إدارة الأدوار والصلاحيات",
    "course.view": "رؤية التكوينات",
    "course.create": "إنشاء تكوينات",
    "course.update": "تعديل التكوينات",
    "course.archive": "أرشفة التكوينات",
    "course.assign_professor": "إسناد المكوِّنين",
    "schedule.view": "رؤية التوقيت",
    "schedule.manage": "إدارة التوقيت",
    "enrollment.view": "رؤية التسجيلات",
    "enrollment.create": "تسجيل المتربصين",
    "enrollment.update": "تعديل التسجيلات",
    "enrollment.cancel": "إلغاء التسجيلات",
    "assessment.view": "رؤية التقييمات",
    "assessment.manage": "إنشاء التقييمات وتعديلها",
    "score.view": "رؤية النقاط",
    "score.enter": "إدخال النقاط وتصحيحها",
    "score.publish": "نشر النقاط للمتربصين",
    "payment.view": "رؤية الدفعات",
    "payment.create": "تسجيل الدفعات",
    "payment.approve": "المصادقة على الدفعات",
    "payment.reject": "رفض الدفعات",
    "payment.cancel": "إلغاء الدفعات المعلَّقة",
    "proof.upload": "إرفاق إثباتات الدفع",
    "proof.view": "فتح إثباتات الدفع",
    "review.create": "كتابة تقييم",
    "review.view": "رؤية التقييمات",
    "review.moderate": "مراجعة التقييمات",
    "notification.send": "إرسال الإشعارات",
    "report.view_operational": "تشغيل التقارير التشغيلية",
    "report.view_financial": "تشغيل التقارير المالية",
    "report.export": "تصدير التقارير",
    "audit.view": "قراءة سجل التدقيق",
    "settings.manage": "إدارة إعدادات النظام",
    groupLogistics: "اللوجستيك",
    "logistics.view": "الاطلاع على الجرد",
    "logistics.manage": "إضافة وتعديل وحذف العتاد",
    "expense.view": "الاطلاع على المصاريف",
    "expense.manage": "تسجيل وتعديل المصاريف",
    groupAttendance: "الحضور",
    "attendance.view": "الاطلاع على أوراق الحضور",
    "attendance.record": "تسجيل الحضور وتصحيحه",
  },
};
