/**
 * English — the source dictionary.
 *
 * Every other language is typed against this one (`const fr: Dict = {...}`),
 * so a key that is missing or misspelled in French or Arabic is a compile
 * error rather than an English word appearing in the middle of an Arabic
 * sentence. Adding a string here breaks the build until all three say it.
 *
 * Values are plain strings with `{name}` placeholders rather than functions,
 * because the active dictionary crosses into client components as a prop and
 * a function will not serialise.
 *
 * Keys are named for what the string *is*, not for what it says, so a change
 * of wording never means a change of key.
 */

export const en = {
  // ---------------------------------------------------------------- meta --
  meta: {
    language: "Language",
    changeLanguage: "Change language",
  },

  // -------------------------------------------------------------- common --
  common: {
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    confirm: "Confirm",
    open: "Open",
    back: "Back",
    search: "Search",
    filter: "Filter",
    filters: "Filters",
    clear: "Clear",
    clearAll: "Clear all",
    apply: "Apply",
    optional: "optional",
    required: "required",
    loading: "Loading",
    none: "None",
    any: "Any",
    all: "All",
    yes: "Yes",
    no: "No",
    more: "More",
    of: "of",
    previous: "Previous",
    next: "Next",
    retry: "Try again",
    toDashboard: "Back to the dashboard",
  },

  // --------------------------------------------------------------- roles --
  // The five roles, as the backend names them. Not translated data — these
  // are the interface's own words for a code the API sends.
  roles: {
    OWNER: "Owner",
    ADMIN: "Administrator",
    RECEPTION: "Reception",
    PROFESSOR: "Instructor",
    STUDENT: "Student",
  },

  // ------------------------------------------------------------ statuses --
  // One vocabulary for the whole application. A payment badge and an
  // enrolment badge must not drift apart in any language.
  status: {
    PENDING: "Pending",
    APPROVED: "Approved",
    REJECTED: "Rejected",
    CANCELLED: "Cancelled",
    ACTIVE: "Active",
    COMPLETED: "Completed",
    SUSPENDED: "Suspended",
    DROPPED: "Dropped",
    DRAFT: "Draft",
    ARCHIVED: "Archived",
    HIDDEN: "Hidden",
    INACTIVE: "Inactive",
    RUNNING: "Running",
    READY: "Ready",
    FAILED: "Failed",
    CLEAN: "Clean",
    INFECTED: "Infected",
    PUBLISHED: "Published",
    FINISHED: "Finished",
    // Inventory: what state a thing is in, and where it is.
    AVAILABLE: "Available",
    IN_USE: "In use",
    UNDER_REPAIR: "Under repair",
    MISSING: "Missing",
    NEW: "New",
    GOOD: "Good",
    NEEDS_REPAIR: "Needs repair",
    DAMAGED: "Damaged",
    // Attendance: a mark on a register, and the register's own state.
    PRESENT: "Present",
    ABSENT: "Absent",
    LATE: "Late",
    OPEN: "Open",
    SUBMITTED: "Submitted",
  },

  // ----------------------------------------------------------------- nav --
  nav: {
    groupWork: "Work",
    groupPeople: "People",
    groupOversight: "Oversight",
    dashboard: "Dashboard",
    courses: "Courses",
    enrollments: "Enrolments",
    schedules: "Schedule",
    grades: "Grades",
    payments: "Payments",
    users: "People",
    reviews: "Reviews",
    notifications: "Notifications",
    reports: "Reports",
    audit: "Audit log",
    account: "Your account",
    main: "Main",
    openNavigation: "Open navigation",
    closeNavigation: "Close navigation",
    navigation: "Navigation",
    toDashboard: "SM Academy — dashboard",
    logistics: "Logistics",
    attendance: "Attendance",
    settings: "Settings",
  },

  // --------------------------------------------------------------- shell --
  shell: {
    notifications: "Notifications",
    notificationsWithCount: "Notifications, {count} unread",
    unread: "unread",
    accountMenu: "Account",
    yourAccount: "Your account",
    signOut: "Sign out",
    signingOut: "Signing out…",
  },

  // -------------------------------------------------- shared components --
  ui: {
    pages: "Pages",
    updatingList: "Updating the list",
    chooseOne: "Choose one",
    loadMore: "Load more",
    loadingPage: "Loading page",
    loadingRows: "Loading rows",
    loadingFigures: "Loading figures",
    loadingDetails: "Loading details",
    loadingSchedule: "Loading the schedule",
    unsavedChanges: "Unsaved changes",
    serverUnreachable: "Could not reach the server.",
  },

  /*
   * Nouns that follow a count: "45 payments".
   *
   * Arabic puts a singular after a number above ten, which is why these are
   * one form per language rather than an English plural translated word for
   * word.
   */
  units: {
    payments: "payments",
    people: "people",
    courses: "courses",
    enrollments: "enrolments",
    reviews: "reviews",
    notifications: "notifications",
    students: "students",
    items: "items",
    expenses: "expenses",
    months: "months",
    registers: "registers",
    records: "records",
  },

  // --------------------------------------------------------------- login --
  login: {
    title: "Sign in",
    lede: "Your identifier is the one printed on your card. Accounts are issued by the academy — there is no public registration.",
    identifier: "ID or phone number",
    identifierHint:
      "The identifier printed on your card, or the number you registered.",
    identifierPlaceholder: "STU-000042",
    password: "Password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    submit: "Sign in",
    submitting: "Signing in…",
    unreachable: "Could not reach the server. Try again.",
    lostPassword:
      "Lost your password? Ask reception to reset it — they can issue a new one, but nobody can read your old one.",
    claim: "Every figure on your screen is one the server decided you may see.",
    tagline: "Skills today, success tomorrow",
    trades: {
      mechanics: "Mechanics",
      it: "IT & Coding",
      electrical: "Electrical",
      automotive: "Automotive",
      networking: "Networking",
    },
    principles: {
      permissionsTitle: "Permissions, not hidden buttons",
      permissionsBody:
        "Five roles share one set of screens. What differs is which columns arrive — an instructor's roster carries no price, because the price is never sent.",
      moneyTitle: "Recorded by one, approved by another",
      moneyBody:
        "Whoever takes a payment cannot be the one who confirms it arrived. Approved entries are final; a correction is a new record, never an edit.",
      trailTitle: "Nothing is deleted",
      trailBody:
        "Accounts are deactivated, enrolments cancelled, reviews hidden. The trail of who did what, and when, survives all of it.",
    },
  },

  // --------------------------------------------------------------- empty --
  empty: {
    errorTitle: "This could not be loaded",
    errorBody: "The request did not come back. Refreshing usually settles it.",
    notFoundTitle: "This page does not exist",
    notFoundBody:
      "The link may be old, or the record may have been removed from your view.",
    notFound: "Not found",
    noAccessTitle: "{what} is not part of your role",
    noAccessSubject: "This screen",
    noAccessBody:
      "Nothing here is hidden from you — the records behind this screen are never sent to your account at all. If you need it, an owner can grant the permission.",
    crashTitle: "This page did not load",
    crashBody:
      "It stopped rather than show you something wrong. Nothing you were doing has been saved.",
    crashExplain:
      "Something went wrong on the way here. Nothing you were doing has been saved or changed — trying again is safe.",
    notFoundExplain:
      "There is no record here for you. Either it does not exist, or it is not one your role can reach — and the platform does not distinguish between those two on purpose.",
    reference: "Reference",
    nothing: "Nothing here yet.",
  },

  /*
   * Sentences with a number in them.
   *
   * These are the strings that most need a placeholder rather than a template
   * literal: "{count} payments" and its Arabic equivalent do not put the
   * number in the same place, and building the sentence with `${}` in the
   * component fixes English word order into all three languages.
   */
  phrases: {
    seatsTaken: "{taken} of {capacity} seats taken",
    seatsLeft: "{count} left",
    allTime: "{total} all time",
    onRecord: "{count} on record",
    draftFinished: "{draft} draft · {finished} finished",
    countPayments: "{count} payments",
    assessmentsMarked: "{marked} of {total} assessments marked",
    studentsMarked: "{marked} of {total} students marked",
    marksEntered: "{created} entered, {updated} corrected.",
    correctedOne: "One of these was corrected after it was first entered.",
    correctedMany:
      "{count} of these were corrected after they were first entered.",
    proofsAttached: "{count} attached",
    pendingApproval: "{id} is pending approval.",
    paidOf: "{paid} paid of {total}",
    countsAgainstBalance: "{amount} now counts against the balance.",
    closedInLedger: "{id} is closed. The record stays in the ledger.",
    overSizeLimit:
      "{size} is over the 10 MB limit. A photo of a slip is usually well under it.",
    rowsExported: "{count} rows.",
    starRating: "{count} stars",
    outOfFive: "{count} out of 5",
    createdAs: "{name} is {id}.",
    enrolledOn: "{name} is now on {course}.",
  },

  // Table column headings.
  columns: {
    name: "Name",
    contact: "Contact",
    status: "Status",
    level: "Level",
    wilaya: "Wilaya",
    runs: "Runs",
    age: "Age",
    type: "Type",
    mark: "Mark",
    average: "Average",
    percent: "Percent",
    action: "Action",
    onWhat: "On what",
  },

  // The labels above the filter controls on a list screen.
  filters: {
    status: "Status",
    search: "Search",
    role: "Role",
    course: "Course",
    student: "Student",
    day: "Day",
    method: "Method",
    who: "Who",
    from: "From",
    to: "To",
    category: "Category",
    condition: "Condition",
    location: "Room",
    month: "Month",
    year: "Year",
  },

  // ----------------------------------------------------------- dashboard --
  dashboard: {
    title: "Dashboard",
    morning: "Good morning",
    afternoon: "Good afternoon",
    evening: "Good evening",
    errorTitle: "The dashboard could not be loaded",
    errorBody:
      "The figures did not come back from the server. Refreshing usually settles it.",
    blurbOwner: "Here is what is happening at SM Academy today.",
    blurbAdmin: "Operations across the institute.",
    blurbReception:
      "Today at the desk — enrolments, payments and the approval queue.",
    blurbProfessor: "What is next, and what is still waiting to be marked.",
    blurbStudent: "Your courses, marks and payments in one place.",
    attention: "Needs attention",
    attentionNote: "Waiting on a person, not on time.",
    awaitingApproval: "Awaiting approval",
    awaitingApprovalNote: "Recorded, not yet approved",
    unmarked: "Assessments unmarked",
    unmarkedNote: "No marks entered yet",
    toModerate: "Reviews to moderate",
    toModerateNote: "Waiting for a decision",
    money: "Money",
    moneyNote: "Approved payments only. Pending money is not revenue yet.",
    collected: "Collected this month",
    collectedNote: "{total} all time",
    outstanding: "Outstanding",
    outstandingNote: "Contracted minus approved, over live enrolments",
    teaching: "Teaching",
    activeCourses: "Active courses",
    liveEnrollments: "Live enrolments",
    myCourses: "My courses",
    yourCourses: "Your courses",
    myStudents: "My students",
    people: "People",
    activeStudents: "Active students",
    professors: "Instructors",
    reception: "Reception",
    administrators: "Administrators",
    today: "Today",
    enrollmentsToday: "Enrolments today",
    paymentsToday: "Payments recorded today",
    nextClass: "Next class",
    openClass: "Open class",
    enrolledCount: "{count} enrolled",
    yourBalance: "Your balance",
    stillToPay: "Still to pay",
    allPaidUp: "Nothing outstanding. You are all paid up.",
    settled: "Settled",
    agreed: "Agreed",
    paid: "Paid",
    remaining: "Remaining",
    paidOfTotal: "{paid} paid of {total}",
    quickActions: "Quick actions",
    recordPayment: "Record a payment",
    enrolStudent: "Enrol a student",
    addPerson: "Add a person",
    reviewPending: "Review pending payments",
    enterMarks: "Enter marks",
    runReport: "Run a report",
    yourTimetable: "Your timetable",
    yourMarks: "Your marks",
  },

  // --------------------------------------------------------------- users --
  users: {
    title: "People",
    lede: "Accounts are deactivated, never deleted — enrolments, payments and marks have to stay attributable to someone.",
    ledeSelf:
      "The details we hold for you. Ask reception to correct anything that is wrong.",
    errorTitle: "People could not be loaded",
    searchPlaceholder: "Name, ID or phone",
    newPerson: "New person",
    newPersonLede:
      "There is no public registration — every account is created here by staff, and the roles you can hand out are bounded by your own.",
    emptyTitle: "Nobody matches these filters",
    emptyBody:
      "Accounts you cannot reach are not listed at all — the search only covers the people your role can see.",
    lastSeen: "Last seen",
    studentRecord: "Student record",
    professorRecord: "Instructor record",
    dateOfBirth: "Date of birth",
    priorLevel: "Prior level",
    emergencyContact: "Emergency contact",
    emergencyPhone: "Emergency phone",
    staffNotes: "Staff notes",
    specialisation: "Specialisation",
    hourlyRate: "Hourly rate",
    qualifications: "Qualifications",
    hiredOn: "Hired on",
    address: "Address",
    wilaya: "Wilaya",
    notGiven: "Not given",
    notAssessed: "Not assessed",
    whoTheyAre: "Who they are",
    contactHint:
      "A phone number or an email is how they are reached; the identifier is how they sign in.",
    role: "Role",
    chooseRole: "Choose a role",
    roleHint:
      "Decides which dashboard they land on, and which fields below apply.",
    firstName: "First name",
    lastName: "Last name",
    phone: "Phone",
    phoneHint: "Stored in international form. 0555 12 34 56 is fine.",
    email: "Email",
    optionalLater: "Everything here is optional and can be filled in later.",
    dobHint: "Age is worked out from this, not stored.",
    createAccount: "Create account",
    accountCreated: "Account created",
    roles: "Roles",
    rolesNote:
      "A role is a set of permissions, not a label. The primary one decides which dashboard they land on.",
    grantRole: "Grant {role}",
    revokeRole: "Revoke {role}",
    roleGranted: "{role} granted",
    roleRevoked: "{role} revoked",
    accountStatus: "Account status",
    accountStatusNote:
      "Accounts are deactivated, never deleted — their enrolments, payments and marks stay attributable.",
    reason: "Reason",
    reasonPlaceholder: "Left the institute at the end of the term.",
    reasonNote: "Recorded in the audit log beside who made the change.",
    reactivate: "Reactivate",
    suspend: "Suspend",
    deactivate: "Deactivate",
    cannotChangeStatus: "Your role cannot change this account's status.",
    reactivated: "Account reactivated",
    reactivatedNote: "They will be able to sign in again.",
    suspended: "Account suspended",
    deactivated: "Account deactivated",
    deactivatedNote:
      "They are signed out on their next request and cannot sign back in. Their records stay exactly where they are.",
    resetPasswordTitle: "Reset this password?",
    resetPassword: "Reset password",
    resetPasswordNote:
      "Every session they have open stops working immediately, and the new password is shown to you once.",
    newPasswordOnce: "Give this to them now. It is not shown again.",
    primary: "primary",
  },

  // ------------------------------------------------------------- courses --
  courses: {
    title: "Courses",
    lede: "The catalogue. A course carries its own price, and each enrolment freezes the price it was made at — so changing one here never rewrites last term's invoices.",
    errorTitle: "Courses could not be loaded",
    searchPlaceholder: "Title or ID",
    emptyTitle: "No courses match these filters",
    emptyBody: "Clear the filters to see the whole catalogue.",
    taughtBy: "Taught by",
    unassigned: "Unassigned",
    price: "Price",
    priceNote: "Frozen onto each enrolment as it is made",
    seats: "Seats",
    uncapped: "Uncapped",
    weeklySchedule: "Weekly schedule",
    weeklyScheduleNote: "A recurring pattern, not a diary of dated sessions.",
    fullTimetable: "Full timetable",
    assessments: "Assessments",
    assessmentsNote:
      "Each carries a weight, which is its share of the course average.",
    noAssessments: "No assessments yet",
    noAssessmentsBody:
      "Marks and averages appear here once an assessment exists on this course.",
    onlyPublished: "Only published assessments show a mark.",
    yourEnrollment: "Your enrolment",
    gradebook: "Gradebook",
    yourMarks: "Your marks",
    published: "Published",
    notPublished: "Not published",
  },

  // --------------------------------------------------------- enrollments --
  enrollments: {
    title: "Enrolments",
    titleSelf: "Your enrolments",
    lede: "One row per student per course, with the price agreed at the time. Payments and marks hang off these, which is why they are cancelled rather than deleted.",
    errorTitle: "Enrolments could not be loaded",
    emptyTitle: "No enrolments match these filters",
    emptyBody:
      "An enrolment is one student on one course. Clear the filters to see them all.",
    agreedPrice: "Agreed price",
    enrolled: "Enrolled",
    enrolOne: "Enrol a student",
    enrolLede:
      "One student, one course. Everything else — payments, marks, a review — hangs off the enrolment this creates.",
    detailTitle: "Enrolment",
    detailLede:
      "One student, one course — and everything attached to that pairing.",
    course: "Course",
    profile: "Profile",
    priceAgreed: "Price agreed at enrolment",
    student: "Student",
    chooseStudent: "Choose a student",
    chooseStudentHint: "Active student accounts only.",
    chooseCourse: "Choose a course",
    chooseCourseHint: "Draft and active courses accept enrolments.",
    notes: "Notes",
    notesPlaceholder: "Paying in three instalments; sibling of STU-000004.",
    notesHint: "They are notified, and the enrolment starts active.",
    whatWillBeRecorded: "What will be recorded",
    courseRuns: "Course runs",
    priceFrozen: "Price, frozen at enrolment",
    submit: "Enrol student",
    done: "Enrolled",
    balance: "Balance",
    balanceNote: "Computed from the payment rows on every read, never stored.",
    frozenAtEnrollment: "Frozen at enrolment",
    approvedPayments: "Approved payments",
    awaitingApproval: "Awaiting approval",
    notCountedAsPaid: "Not counted as paid",
    remaining: "Remaining",
    stillOwed: "Still owed",
    outstanding: "Outstanding",
    payments: "Payments",
    paymentsNote:
      "Every entry is recorded first and approved by somebody else.",
    paymentsFor: "Payments for this enrolment",
    noPayments: "Nothing recorded against this enrolment yet",
    noPaymentsBody:
      "Cash taken at the desk, a transfer or a cheque — each is recorded here and then approved.",
    reference: "Reference",
  },

  // -------------------------------------------------------------- grades --
  grades: {
    title: "Grades",
    lede: "Averages are worked out from the raw marks every time they are asked for, never stored. Change an assessment's weight and every average moves with it.",
    scopeNote: "The gradebook is scoped to the courses you are assigned to.",
    noCourses: "No courses assigned to you",
    noCoursesBody: "A gradebook appears here once you are assigned to a course.",
    chooseCourse: "Choose a course",
    chooseCourseBody: "Pick one above to see its gradebook and mark sheets.",
    markSheets: "Mark sheets",
    markSheetsNote: "Open one to enter or correct marks.",
    noAssessments: "No assessments on this course",
    noAssessmentsBody:
      "Marks are entered against an assessment, so one has to exist before the sheet does.",
    gradebook: "Gradebook",
    nobodyEnrolled: "Nobody is enrolled in this course yet",
    nobodyEnrolledBody:
      "The gradebook fills in as students are enrolled and assessments are marked.",
    notMarkedYet: "Not marked yet",
    yourMarks: "Your marks",
    yourMarksLede:
      "Published results only. A mark appears here once your instructor releases the assessment it belongs to.",
    noMarks: "No marks published yet",
    noMarksBody:
      "Your instructor releases an assessment when the class has been marked. Nothing is hidden from you here — there is simply nothing yet.",
    corrected: "Corrected",
    assessment: "Assessment",
    recorded: "Recorded",
    markSheet: "Mark sheet",
    outOf: "Out of",
    weight: "Weight",
    weightNote: "Its share of the course average",
    marked: "Marked",
    heldOn: "Held on",
    published: "Published",
    notPublished: "Not published",
    student: "Student",
    comment: "Comment",
    history: "History",
    notMarked: "Not marked",
    saveSheet: "Save sheet",
    enterMoves: "Enter or arrow-down moves to the next student.",
    atomicNote: "The sheet saves as one unit: either every mark lands or none does.",
    sheetSaved: "Sheet saved",
    publishTitle: "Publish these marks?",
    publishAction: "Publish marks",
    publishBody:
      "Every student with a mark is notified. This cannot be undone — a wrong mark is corrected, not hidden.",
    notPublishedNote:
      "Students cannot see these marks yet. Publishing notifies everyone who has one.",
    publishedNote: "Every student on the roster has a mark.",
    marksPublished: "Marks published",
    marksPublishedNote: "Everyone with a mark has been notified.",
  },

  // ------------------------------------------------------------ payments --
  payments: {
    title: "Payments",
    lede: "Every entry is recorded, then approved by someone else. Nothing here is edited or deleted — a mistake before approval is cancelled, and one after it is corrected with a new record.",
    errorTitle: "Payments could not be loaded",
    emptyTitle: "No payments match these filters",
    emptyBody: "Clear the filters to see every entry.",
    reference: "Reference",
    noReferenceNote: "Cash taken at the desk normally has none.",
    recordedDecided: "Recorded / decided",
    amount: "Amount",
    student: "Student",
    course: "Course",
    currency: "Currency",
    method: "Method",
    paidOn: "Paid on",
    recordTitle: "Record a payment",
    recordLede:
      "Money that has arrived, against the enrolment it belongs to. Every entry starts pending and is approved by somebody else — you cannot approve one you recorded.",
    enrollment: "Enrolment",
    chooseEnrollment: "Choose a student and course",
    chooseEnrollmentHint:
      "Active enrolments only. Money against a withdrawn one needs a live enrolment first.",
    amountHint: "The amount handed over, in whole units or with centimes.",
    amountPlaceholder: "20000",
    paidOnHint: "The day the money arrived, not today's date if they differ.",
    methodHint: "How it was paid",
    notes: "Notes",
    notesPlaceholder: "Second instalment; receipt number 41.",
    against: "Against",
    loadingBalance: "Loading the balance…",
    agreed: "Agreed",
    paid: "Paid",
    pending: "Pending",
    remaining: "Remaining",
    attachLater: "Attach the bank slip on the payment's own page, once it exists.",
    submit: "Record payment",
    recorded: "Payment recorded",
    pendingNoticeSelf:
      "This entry will be pending. You will not be able to approve it yourself — whoever records a payment cannot be the one who confirms it arrived.",
    pendingNotice:
      "This entry will be pending until somebody with approval rights confirms it. Reception records money; it does not approve it.",
    amountInvalid: "Enter an amount, like 20000 or 20000.50.",
    amountTooSmall: "An amount has to be more than nothing.",
    details: "Details",
    history: "History",
    proof: "Proof",
    decision: "Decision",
    decisionNote: "Recorded by one person, confirmed by another.",
    notRecorder: "Not the person who recorded it",
    selfApproveBlocked: "You recorded this payment. Someone else must approve it.",
    statePending: "Recorded, not yet approved. This is not counted as paid.",
    stateApproved: "Approved and counted against the balance.",
    stateRejected: "Rejected. Nothing was counted.",
    stateCancelled: "Cancelled before any decision was made.",
    reasonForRejection: "Reason for rejection",
    approveTitle: "Approve this payment?",
    approveAction: "Approve payment",
    approveBody:
      "This counts the money against the balance and cannot be undone.",
    approve: "Approve",
    rejectTitle: "Reject this payment?",
    rejectAction: "Reject payment",
    rejectBody: "The record stays in the ledger with the reason attached.",
    reject: "Reject",
    rejectWhy: "Why is this being rejected?",
    rejectWhyHint: "The person who was refused has to be able to be told why.",
    cancelTitle: "Cancel this entry?",
    cancelAction: "Cancel entry",
    cancelBody:
      "For an entry that should not have been made. It stays in the ledger, closed.",
    cancelWhy: "Why is this being cancelled?",
    cancelWhyPlaceholder: "Recorded against the wrong enrolment.",
    reasonShown: "Recorded against the payment and shown to whoever reads it.",
    approved: "Payment approved",
    rejected: "Payment rejected",
    cancelled: "Entry cancelled",
    noProof: "No proof attached.",
    proofAttached: "Proof attached",
    proofScanNote: "It is scanned before anyone can open it.",
    scanning:
      "Still being checked. A file is not handed out before it is scanned.",
    scanned: "Scanned",
    uploading: "Uploading…",
    attachProof: "Attach a proof",
    downloadFailed: "Could not prepare the download.",
    storageRefused: "The file was refused by the storage service.",
    uploadIncomplete: "The upload did not complete.",
  },

  // ------------------------------------------------------------- reviews --
  reviews: {
    title: "Reviews",
    lede: "Written by students who finished a course. Nothing is deleted — hiding or rejecting keeps the row, the decision and who made it.",
    ledeProfessor:
      "What students said about the courses you can see. Approved reviews only, and never with the author's name attached for an instructor.",
    errorTitle: "Reviews could not be loaded",
    byCourse: "By course",
    byCourseNote:
      "Approved reviews only, worked out on read. A stored average could not be re-derived once a review is hidden.",
    awaitingModeration: "Awaiting moderation",
    nothingToModerate: "Nothing to moderate",
    caughtUp:
      "You are all caught up. New reviews arrive as students finish their courses.",
    emptyTitle: "No reviews here yet",
    noComment: "No comment left.",
    anonymous: "Anonymous",
    replyFromInstitute: "Reply from the institute",
    publicReply: "Public reply",
    publicReplyNote: "Published alongside the review if you approve it.",
    moderate: "Moderate",
    changeDecision: "Change decision",
    approve: "Approve",
    reject: "Reject",
    rejectTitle: "Reject this review?",
    rejectAction: "Reject review",
    rejectBody:
      "It stays in the record with your decision against it, and never appears publicly.",
    approved: "Review approved",
    hidden: "Review hidden",
    rejected: "Review rejected",
    keptNote: "The row, the decision and who made it are all kept.",
    writeTitle: "Review a course",
    writeNote: "Your instructor never learns who wrote it.",
    rating: "Rating",
    comment: "Comment",
    commentPlaceholder: "What was good, what could be better.",
    submit: "Submit review",
    submitted: "Review submitted",
  },

  // ----------------------------------------------------------- schedules --
  schedules: {
    title: "Schedule",
    lede: "A recurring weekly pattern, not a diary of dated sessions. Each slot runs every week between its effective dates.",
    errorTitle: "The schedule could not be loaded",
    emptyTitle: "No classes scheduled",
    emptyBody:
      "Your weekly schedule will appear here when a course is assigned.",
    session: "Class",
  },

  // ------------------------------------------------------------- reports --
  reports: {
    title: "Reports",
    lede: "Every figure is read from the rows on each request — nothing is cached and nothing is stored, so the totals reconcile against the ledger by construction.",
    noneForRole: "No reports for your role",
    noneForRoleBody:
      "Reading a report is its own permission, granted separately from the screens the figures come from.",
    errorTitle: "That report could not be run",
    errorBody:
      "The query did not come back. Narrowing the date range and trying again usually settles it.",
    totals: "Totals",
    rows: "Rows",
    emptyTitle: "Nothing matches these filters",
    emptyBody: "Widen the date range, or clear the course, to see more rows.",
    enrollmentsTitle: "Enrolments",
    enrollmentsNote: "Head-count per course, by status. No money in it at all.",
    revenueTitle: "Revenue",
    revenueNote: "Money actually collected, by course. Approved payments only.",
    outstandingTitle: "Outstanding",
    outstandingNote: "What each live enrolment still owes.",
    unsettledOnly: "Unsettled only",
    export: "Export",
    exportNote: "A CSV of exactly the rows above, built in the background.",
    exportBuilding: "Building the file…",
    exportDownload: "Download",
    exportNothingQueued: "Nothing queued yet.",
    exportPrivate: "Private",
    exportTooLong: "The export is taking longer than expected. Check back later.",
    exportReady: "Export ready",
    exportLost: "Lost track of the export. Reload to see its state.",
    exportAgain: "Export again",
    exportCsv: "Export CSV",
    exportFailed: "The export failed.",
  },

  // --------------------------------------------------------------- audit --
  audit: {
    title: "Audit log",
    lede: "Append-only, enforced by the database rather than by convention — there is no endpoint that edits or deletes a row at any version, and the actions most worth recording here are exactly the ones someone would want to erase.",
    errorTitle: "The log could not be read",
    emptyTitle: "Nothing recorded for these filters",
    emptyBody:
      "The log holds every consequential action. If this is empty, none of them match — not that none happened.",
    loadMore: "Load more",
    endOfTrail: "That is the whole trail.",
    loadMoreFailed: "Could not load more.",
    actions: {
      loginFailed: "Failed login",
      userCreated: "User created",
      userUpdated: "User updated",
      userStatusChanged: "User status changed",
      passwordReset: "Password reset",
      roleGranted: "Role granted",
      roleRevoked: "Role revoked",
      studentEnrolled: "Student enrolled",
      markChanged: "Mark changed",
      marksPublished: "Marks published",
      paymentRecorded: "Payment recorded",
      paymentApproved: "Payment approved",
      paymentRejected: "Payment rejected",
      proofDownloaded: "Proof downloaded",
      reviewModerated: "Review moderated",
      reportExported: "Report exported",
      exportDownloaded: "Export downloaded",
    },
    subjects: {
      enrollment: "An enrolment",
      reportExport: "An export",
      person: "A person",
      payment: "A payment",
      course: "A course",
      review: "A review",
    },
  },

  // ------------------------------------------------------- notifications --
  notifications: {
    title: "Notifications",
    lede: "Told to you and nobody else — an enrolment made in your name, a mark released, a payment decided.",
    errorTitle: "Notifications could not be loaded",
    unreadOnly: "Unread",
    markAllRead: "Mark all as read",
    allMarkedRead: "All marked as read",
    nothingUnread: "Nothing unread",
    caughtUp: "You are all caught up.",
    all: "All",
    emptyTitle: "No notifications yet",
    emptyBody:
      "You will hear about the things that concern you — an enrolment, a mark released, a payment decided.",
  },

  // ------------------------------------------------------------- account --
  account: {
    title: "Your account",
    lede: "What we hold about you, and what your role lets you reach.",
    fullRecord: "Full record",
    lastSignedIn: "Last signed in",
    permissionsTitle: "What your role allows",
    permissionsNote:
      "Granted by permission, not by job title. The server checks every one of these on every request.",
    password: "Password",
    passwordNote:
      "Changed here, by you. Nobody can read your existing one — it was never stored in a readable form.",
    current: "Current password",
    newPassword: "New password",
    newPasswordHint:
      "Long beats complicated. A phrase you can remember is stronger than a word with symbols in it.",
    repeat: "Repeat the new password",
    submit: "Change password",
    changed: "Password changed",
    changedNote: "Use the new one the next time you sign in.",
    mismatch: "These two do not match.",
    correctionNote:
      "Something wrong here? Ask reception to correct it — changes to a person's record are made in one place, where they are recorded.",
    sessionNote:
      "Changing your password does not sign you out of this browser. If you think somebody else has been using your account, tell an administrator.",
  },

  /*
   * The permission catalogue, in words.
   *
   * The codenames come from the backend and are never translated — they are
   * identifiers. These are the sentences beside them on the account screen.
   */

  // ----------------------------------------------------------- logistics --

  // --------------------------------------------------------------- print --

  // ---------------------------------------------------------- attendance --

  // ------------------------------------------------------------ settings --
  settings: {
    title: "Settings",
    lede: "The institute's own details. They open every printed document, so what is here is what appears on a receipt handed to a parent.",
    errorTitle: "Settings could not be loaded",
    identity: "Identity",
    identityLede: "The name on the sign outside, and the formal name if it differs.",
    contact: "Address and contact",
    contactLede: "Printed under the name on every report. Anything left blank is simply left off the page.",
    documents: "Printed documents",
    documentsLede: "What appears at the foot of every page, beside the page number.",
    name: "Organisation name",
    legalName: "Legal name",
    addressLine: "Street address",
    city: "City",
    wilaya: "Wilaya",
    phone: "Phone",
    email: "Email",
    website: "Website",
    registrationNumber: "Registration number",
    tagline: "Tagline",
    printFooter: "Page footer",
    saved: "Settings saved",
    readOnly: "These details are managed by the owner. You can see what appears on printed documents but not change it.",
    logoNote: "The logo is the official artwork in the application itself and is not edited here — a second copy uploaded through a form is how an institute ends up with two logos and no answer about which is current.",
    previewTitle: "How a document opens",
  },
  attendance: {
    title: "Attendance",
    lede: "One register per class per day. A register nobody has taken is empty, which is not the same as everybody being away.",
    errorTitle: "Attendance could not be loaded",
    emptyTitle: "No registers yet",
    emptyBody: "Open one for a class and a date, and the whole roster appears ready to mark.",
    openRegister: "Open a register",
    openRegisterLede: "Pick the class and the day. If somebody has already opened it, you will be taken to theirs rather than making a second one.",
    takeRegister: "Take the register",
    saveRegister: "Save the register",
    saved: "Register saved",
    savedDetail: "{created} marked, {updated} corrected.",
    heldOn: "Date",
    classLabel: "Class",
    topic: "Topic",
    topicHint: "What was covered, if it is worth recording.",
    room: "Room",
    marked: "Marked",
    roster: "On the roster",
    present: "Present",
    absent: "Absent",
    late: "Late",
    rate: "Rate",
    minutesLate: "Minutes late",
    note: "Note",
    markAllPresent: "Mark everyone present",
    clearAll: "Clear all",
    corrected: "Corrected",
    correctedNote: "This mark was changed after it was first entered.",
    summary: "Attendance summary",
    summaryLede: "Rates over the period, per student. Late counts as attended.",
    noRate: "No register taken",
    notOnRoster: "Nobody is enrolled on this class yet.",
    readOnly: "You can see attendance and print it. Taking a register belongs to the class's instructor.",
    printRegister: "Print the register",
    printSummary: "Print the attendance report",
    blankSheet: "A register that has not been taken prints as a blank sheet, ready to fill in by hand.",
  },
  print: {
    print: "Print",
    printThis: "Print this list",
    savePdf: "Save as PDF",
    preview: "Print preview",
    generated: "Generated",
    pageOf: "Page {page} of {total}",
    dialogHint: "The print dialog opens on its own. Your browser's “Save as PDF” destination produces the same document as a file.",
    nothingToPrint: "There is nothing to print for this selection.",
    truncated: "This document shows the first 2,000 records of a larger selection. Narrow the filters to print the rest.",
    filteredNotice: "This is a filtered selection, not the whole list.",
    openInNewTab: "Opens a printable A4 sheet in a new tab.",
    studentList: "STUDENT LIST",
    staffList: "STAFF LIST",
    studentProfile: "STUDENT PROFILE",
    courseList: "COURSE LIST",
    classList: "CLASS LIST",
    enrollmentList: "ENROLMENT LIST",
    scheduleTitle: "CLASS SCHEDULE",
    incomeReport: "INCOME REPORT",
    receiptTitle: "PAYMENT RECEIPT",
    financialSummary: "FINANCIAL SUMMARY",
    attendanceRegister: "ATTENDANCE REGISTER",
    attendanceReport: "ATTENDANCE REPORT",
    managementReport: "MANAGEMENT REPORT",
    gradebookTitle: "GRADE SHEET",
    totalStudents: "Total students",
    totalStaff: "Total staff",
    totalCourses: "Total courses",
    totalEnrollments: "Total enrolments",
    totalRecords: "Total records",
    totalIncome: "Total income",
    totalExpenses: "Total expenses",
    netBalance: "Net balance",
    outstanding: "Outstanding",
    attendanceRate: "Attendance rate",
    preparedBy: "Prepared by",
    signature: "Signature",
    receivedBy: "Received by",
    period: "Period",
    allTime: "All time",
    receiptNumber: "Receipt number",
    amountPaid: "Amount paid",
    remainingBalance: "Remaining balance",
    payer: "Received from",
    forCourse: "For",
    pendingNotice: "This receipt records a payment that is still awaiting approval.",
    incomeByCourse: "Income by course",
    expensesByCategory: "Expenses by category",
    monthByMonth: "Month by month",
    income: "Income",
    expenditure: "Expenditure",
    net: "Net",
    people: "People",
    teaching: "Teaching",
    money: "Money",
    inventory: "Inventory",
    newRegistrations: "New registrations",
    activeStudents: "Active students",
    activeCourses: "Active courses",
    liveEnrollments: "Live enrolments",
    registersTaken: "Registers taken",
    pendingPayments: "Pending payments",
    itemsNeedingRepair: "Items needing repair",
    itemsDamaged: "Damaged items",
    itemsMissing: "Missing items",
    inventoryLines: "Inventory lines",
    inventoryUnits: "Total items",
    registered: "Registered",
    date: "Date",
    time: "Time",
    entries: "Entries",
    balance: "Balance",
    notes: "Notes",
    status: "Status",
    summary: "Summary",
  },
  logistics: {
    title: "Logistics",
    lede: "What the academy owns, and what it costs to keep the doors open. Inventory and monthly expenses in one place.",
    inventory: "Inventory",
    expensesTab: "Expenses",
    historyTab: "Monthly history",
    setupTab: "Categories & rooms",
    readOnly: "You can see everything here and print it. Adding, editing and removing belong to an owner or an administrator.",
    errorTitle: "The inventory could not be loaded",
    emptyTitle: "Nothing in the inventory yet",
    emptyBody: "Record the chairs, desks, machines and equipment the academy owns. Every item can be counted, located and printed.",
    addItem: "Add item",
    editItem: "Edit item",
    itemLede: "One line of the inventory. Identical things are counted together; anything with a serial number is a line of its own.",
    addItemLede: "Categories and rooms are managed on the setup tab, so a new kind of equipment never needs a developer.",
    name: "Item name",
    category: "Category",
    quantity: "Quantity",
    condition: "Condition",
    status: "Status",
    location: "Location / room",
    purchaseDate: "Purchase date",
    purchasePrice: "Purchase price",
    serial: "Serial number",
    notes: "Notes",
    lastUpdated: "Last updated",
    added: "Added",
    reference: "Receipt or reference",
    method: "Payment method",
    amount: "Amount",
    spentOn: "Date paid",
    accountingMonth: "Accounting month",
    description: "Description",
    quantityHint: "How many of this exact item. Never negative.",
    serialHint: "For machines. Two items cannot share one serial number.",
    priceHint: "What it cost, if that is known. Leave it blank if it is not.",
    accountingMonthHint: "The month it belongs to. Follows the date paid — change it when February's bill is paid in March.",
    noCategories: "No categories yet. Add one on the setup tab first.",
    noLocations: "No rooms recorded. An item can be filed without one.",
    totalItems: "Inventory lines",
    totalUnits: "Total items",
    totalUnitsNote: "Counting quantities, not lines.",
    needingRepair: "Needs repair",
    damaged: "Damaged",
    missing: "Missing",
    underRepair: "Under repair",
    available: "Available",
    inUse: "In use",
    categoriesCount: "Categories",
    roomsCount: "Rooms",
    byCategory: "By category",
    byLocation: "By room",
    byCondition: "By condition",
    recentlyAdded: "Recently added",
    lines: "lines",
    expensesTitle: "Monthly expenses",
    expensesLede: "What the institute spent, filed by the month it belongs to rather than the day it happened to be paid.",
    expensesErrorTitle: "The expenses could not be loaded",
    expensesEmptyTitle: "Nothing recorded for this month",
    expensesEmptyBody: "Electricity, water, internet, repairs, cleaning — anything the institute paid for belongs here.",
    addExpense: "Add expense",
    editExpense: "Edit expense",
    addExpenseLede: "One thing the institute paid for. The month's total is worked out by the server, never by this screen.",
    monthTotal: "This month",
    previousMonth: "Previous month",
    yearTotal: "Year to date",
    entriesThisMonth: "Entries this month",
    upOn: "{amount} more than {month}",
    downOn: "{amount} less than {month}",
    sameAs: "The same as {month}",
    firstMonth: "Nothing was recorded in {month}.",
    breakdown: "By category",
    monthlyTotals: "Month by month",
    historyTitle: "Monthly history",
    historyLede: "Every month with something in it, newest first. Open one to read its entries.",
    historyEmptyTitle: "No months recorded yet",
    historyEmptyBody: "Once expenses are recorded, each month appears here with its total and its heaviest category.",
    monthColumn: "Month",
    totalColumn: "Total expenses",
    mainCategory: "Main category",
    entries: "Entries",
    viewMonth: "View",
    setupTitle: "Categories and rooms",
    setupLede: "The labels this section files things under. They are rows, not code — a new kind of equipment is added here, not by a developer.",
    itemCategories: "Item categories",
    expenseCategories: "Expense categories",
    rooms: "Rooms and stores",
    addCategory: "Add category",
    addRoom: "Add room",
    newCategoryPlaceholder: "3D printers",
    newRoomPlaceholder: "Room 3",
    retire: "Retire",
    restore: "Restore",
    retired: "Retired",
    retiredNote: "A retired label leaves the dropdowns. Everything already filed under it keeps its name.",
    filedUnder: "{count} filed under this",
    nothingFiled: "Nothing filed under this yet",
    print: "Print",
    printInventory: "Print logistics list",
    printExpenses: "Print monthly expenses",
    printNow: "Print",
    printHint: "Opens a printable A4 sheet in a new tab.",
    printingDialog: "The print dialog opens on its own. Close this tab when you are done.",
    documentTitle: "LOGISTICS INVENTORY",
    expensesDocumentTitle: "MONTHLY EXPENSES",
    printedOn: "Printed",
    printedTotalItems: "Total items",
    printedTotalLines: "Inventory lines",
    printedTotalExpenses: "Total monthly expenses",
    filteredNotice: "This is a filtered selection, not the whole inventory.",
    nothingToPrint: "There is nothing to print for this selection.",
    deleteItem: "Delete item",
    deleteItemBody: "{name} leaves the inventory and every total immediately. The record of it stays in the audit log.",
    deleteExpense: "Delete expense",
    deleteExpenseBody: "{name} leaves this month's total immediately. The record of it stays in the audit log.",
    itemDeleted: "Item removed",
    expenseDeleted: "Expense removed",
    itemAdded: "Item added",
    itemSaved: "Item saved",
    expenseAdded: "Expense recorded",
    expenseSaved: "Expense saved",
    categoryAdded: "Category added",
    roomAdded: "Room added",
    sectionItem: "The item",
    sectionPurchase: "Purchase and identification",
    sectionExpense: "The expense",
    sectionFiling: "Filing",
  },
  perms: {
    groupUsers: "Users & access",
    groupCatalogue: "Catalogue",
    groupEnrollment: "Enrolment",
    groupMoney: "Money",
    groupEngagement: "Engagement",
    groupOversight: "Oversight",
    "user.view": "See people",
    "user.create": "Create accounts",
    "user.update": "Edit people",
    "user.deactivate": "Deactivate accounts",
    "user.reset_password": "Reset passwords",
    "user.assign_role": "Assign roles",
    "role.manage": "Manage roles and permissions",
    "course.view": "See courses",
    "course.create": "Create courses",
    "course.update": "Edit courses",
    "course.archive": "Archive courses",
    "course.assign_professor": "Assign instructors",
    "schedule.view": "See the schedule",
    "schedule.manage": "Manage the schedule",
    "enrollment.view": "See enrolments",
    "enrollment.create": "Enrol students",
    "enrollment.update": "Edit enrolments",
    "enrollment.cancel": "Cancel enrolments",
    "assessment.view": "See assessments",
    "assessment.manage": "Create and edit assessments",
    "score.view": "See marks",
    "score.enter": "Enter and correct marks",
    "score.publish": "Publish marks to students",
    "payment.view": "See payments",
    "payment.create": "Record payments",
    "payment.approve": "Approve payments",
    "payment.reject": "Reject payments",
    "payment.cancel": "Cancel pending payments",
    "proof.upload": "Attach payment proofs",
    "proof.view": "Open payment proofs",
    "review.create": "Write a review",
    "review.view": "See reviews",
    "review.moderate": "Moderate reviews",
    "notification.send": "Send notifications",
    "report.view_operational": "Run operational reports",
    "report.view_financial": "Run financial reports",
    "report.export": "Export reports",
    "audit.view": "Read the audit log",
    "settings.manage": "Manage system settings",
    groupLogistics: "Logistics",
    "logistics.view": "See the inventory",
    "logistics.manage": "Add, edit and remove inventory",
    "expense.view": "See expenses",
    "expense.manage": "Record and edit expenses",
    groupAttendance: "Attendance",
    "attendance.view": "See registers",
    "attendance.record": "Take and correct registers",
  },
};

/*
 * Deliberately not `as const`. With it, every value would be its own literal
 * type and `const fr: Dict` would be required to repeat the English strings
 * word for word. What the type is for is the *shape*: the same keys, all of
 * them, in all three languages.
 */
export type Dict = typeof en;
