import type { Dict } from "./en";

/**
 * French — the language the office runs on, and the default.
 *
 * Typed against the English dictionary, so a missing key will not compile.
 *
 * Register: vouvoiement throughout, and the vocabulary an Algerian training
 * centre actually uses — *inscription* for an enrolment, *encaisser* for
 * taking money in, *formateur* for the person teaching, *stagiaire* for the
 * person learning a trade. Not the vocabulary of a French university, which
 * would be wrong in a different way from being in the wrong language.
 */

export const fr: Dict = {
  meta: {
    language: "Langue",
    changeLanguage: "Changer de langue",
  },

  common: {
    save: "Enregistrer",
    cancel: "Annuler",
    close: "Fermer",
    confirm: "Confirmer",
    open: "Ouvrir",
    back: "Retour",
    search: "Rechercher",
    filter: "Filtrer",
    filters: "Filtres",
    clear: "Effacer",
    clearAll: "Tout effacer",
    apply: "Appliquer",
    optional: "facultatif",
    required: "obligatoire",
    loading: "Chargement",
    none: "Aucun",
    any: "Tous",
    all: "Tout",
    yes: "Oui",
    no: "Non",
    more: "Plus",
    of: "sur",
    previous: "Précédent",
    next: "Suivant",
    retry: "Réessayer",
    toDashboard: "Retour au tableau de bord",
  },

  roles: {
    OWNER: "Propriétaire",
    ADMIN: "Administrateur",
    RECEPTION: "Accueil",
    PROFESSOR: "Formateur",
    STUDENT: "Stagiaire",
  },

  status: {
    PENDING: "En attente",
    APPROVED: "Validé",
    REJECTED: "Refusé",
    CANCELLED: "Annulé",
    ACTIVE: "Actif",
    COMPLETED: "Terminé",
    SUSPENDED: "Suspendu",
    DROPPED: "Abandonné",
    DRAFT: "Brouillon",
    ARCHIVED: "Archivé",
    HIDDEN: "Masqué",
    INACTIVE: "Inactif",
    RUNNING: "En cours",
    READY: "Prêt",
    FAILED: "Échoué",
    CLEAN: "Sain",
    INFECTED: "Infecté",
    PUBLISHED: "Publié",
    FINISHED: "Terminé",
    // Inventory: what state a thing is in, and where it is.
    AVAILABLE: "Disponible",
    IN_USE: "En service",
    UNDER_REPAIR: "En réparation",
    MISSING: "Manquant",
    NEW: "Neuf",
    GOOD: "Bon état",
    NEEDS_REPAIR: "À réparer",
    DAMAGED: "Endommagé",
    // Attendance: a mark on a register, and the register's own state.
    PRESENT: "Présent",
    ABSENT: "Absent",
    LATE: "En retard",
    OPEN: "Ouverte",
    SUBMITTED: "Enregistrée",
  },

  nav: {
    groupWork: "Travail",
    groupPeople: "Personnes",
    groupOversight: "Contrôle",
    dashboard: "Tableau de bord",
    courses: "Formations",
    enrollments: "Inscriptions",
    schedules: "Planning",
    grades: "Notes",
    payments: "Paiements",
    users: "Personnes",
    reviews: "Avis",
    notifications: "Notifications",
    reports: "Rapports",
    audit: "Journal d'audit",
    account: "Votre compte",
    main: "Principal",
    openNavigation: "Ouvrir la navigation",
    closeNavigation: "Fermer la navigation",
    navigation: "Navigation",
    toDashboard: "SM Academy — tableau de bord",
    logistics: "Logistique",
    attendance: "Présences",
    settings: "Paramètres",
  },

  shell: {
    notifications: "Notifications",
    notificationsWithCount: "Notifications, {count} non lues",
    unread: "non lues",
    accountMenu: "Compte",
    yourAccount: "Votre compte",
    signOut: "Se déconnecter",
    signingOut: "Déconnexion…",
  },

  ui: {
    pages: "Pages",
    updatingList: "Mise à jour de la liste",
    chooseOne: "Choisissez",
    loadMore: "Charger la suite",
    loadingPage: "Chargement de la page",
    loadingRows: "Chargement des lignes",
    loadingFigures: "Chargement des chiffres",
    loadingDetails: "Chargement du détail",
    loadingSchedule: "Chargement du planning",
    unsavedChanges: "Modifications non enregistrées",
    serverUnreachable: "Le serveur est injoignable.",
  },

  units: {
    payments: "paiements",
    people: "personnes",
    courses: "formations",
    enrollments: "inscriptions",
    reviews: "avis",
    notifications: "notifications",
    students: "stagiaires",
    items: "articles",
    expenses: "dépenses",
    months: "mois",
    registers: "feuilles",
    records: "enregistrements",
  },

  login: {
    title: "Connexion",
    lede: "Votre identifiant est celui imprimé sur votre carte. Les comptes sont délivrés par l'académie — il n'y a pas d'inscription publique.",
    identifier: "Identifiant ou numéro de téléphone",
    identifierHint:
      "L'identifiant imprimé sur votre carte, ou le numéro que vous avez déclaré.",
    identifierPlaceholder: "STU-000042",
    password: "Mot de passe",
    showPassword: "Afficher le mot de passe",
    hidePassword: "Masquer le mot de passe",
    submit: "Se connecter",
    submitting: "Connexion…",
    unreachable: "Le serveur est injoignable. Réessayez.",
    lostPassword:
      "Mot de passe perdu ? Demandez à l'accueil de le réinitialiser — on peut vous en délivrer un nouveau, mais personne ne peut lire l'ancien.",
    claim:
      "Chaque chiffre affiché à l'écran est un chiffre que le serveur a décidé de vous montrer.",
    tagline: "Des compétences aujourd'hui, la réussite demain",
    trades: {
      mechanics: "Mécanique",
      it: "Informatique & code",
      electrical: "Électricité",
      automotive: "Automobile",
      networking: "Réseaux",
    },
    principles: {
      permissionsTitle: "Des permissions, pas des boutons cachés",
      permissionsBody:
        "Cinq rôles partagent les mêmes écrans. Ce qui change, ce sont les colonnes qui arrivent — la liste d'un formateur ne porte aucun tarif, parce que le tarif ne lui est jamais envoyé.",
      moneyTitle: "Encaissé par l'un, validé par l'autre",
      moneyBody:
        "Celui qui encaisse ne peut pas être celui qui confirme la réception. Une écriture validée est définitive ; une correction est une nouvelle écriture, jamais une modification.",
      trailTitle: "Rien n'est supprimé",
      trailBody:
        "Les comptes sont désactivés, les inscriptions annulées, les avis masqués. La trace de qui a fait quoi, et quand, survit à tout cela.",
    },
  },

  empty: {
    errorTitle: "Impossible de charger cette page",
    errorBody:
      "La requête n'est pas revenue. Une actualisation suffit généralement.",
    notFoundTitle: "Cette page n'existe pas",
    notFoundBody:
      "Le lien est peut-être ancien, ou l'enregistrement a été retiré de votre vue.",
    notFound: "Introuvable",
    noAccessTitle: "{what} ne fait pas partie de votre rôle",
    noAccessSubject: "Cet écran",
    noAccessBody:
      "Rien ne vous est caché ici — les enregistrements derrière cet écran ne sont jamais envoyés à votre compte. Si vous en avez besoin, un propriétaire peut vous accorder la permission.",
    crashTitle: "Cette page ne s'est pas chargée",
    crashBody:
      "Elle s'est arrêtée plutôt que de vous montrer quelque chose de faux. Rien de ce que vous faisiez n'a été enregistré.",
    crashExplain:
      "Quelque chose s'est mal passé en chemin. Rien de ce que vous faisiez n'a été enregistré ni modifié — réessayer est sans risque.",
    notFoundExplain:
      "Il n'y a ici aucun enregistrement pour vous. Soit il n'existe pas, soit votre rôle ne permet pas de l'atteindre — et la plateforme ne fait pas la différence entre les deux, délibérément.",
    reference: "Référence",
    nothing: "Rien pour l'instant.",
  },

  phrases: {
    seatsTaken: "{taken} places prises sur {capacity}",
    seatsLeft: "{count} restantes",
    allTime: "{total} depuis le début",
    onRecord: "{count} au dossier",
    draftFinished: "{draft} en brouillon · {finished} terminées",
    countPayments: "{count} paiements",
    assessmentsMarked: "{marked} évaluations corrigées sur {total}",
    studentsMarked: "{marked} stagiaires notés sur {total}",
    marksEntered: "{created} saisies, {updated} corrigées.",
    correctedOne: "L'une d'elles a été corrigée après sa première saisie.",
    correctedMany:
      "{count} d'entre elles ont été corrigées après leur première saisie.",
    proofsAttached: "{count} joint",
    pendingApproval: "{id} est en attente de validation.",
    paidOf: "{paid} payés sur {total}",
    countsAgainstBalance: "{amount} est désormais décompté du solde.",
    closedInLedger: "{id} est clos. L'écriture reste au registre.",
    overSizeLimit:
      "{size} dépasse la limite de 10 Mo. La photo d'un bordereau y reste largement inférieure.",
    rowsExported: "{count} lignes.",
    starRating: "{count} étoiles",
    outOfFive: "{count} sur 5",
    createdAs: "{name} porte l'identifiant {id}.",
    enrolledOn: "{name} est désormais inscrit à {course}.",
  },

  columns: {
    name: "Nom",
    contact: "Contact",
    status: "Statut",
    level: "Niveau",
    wilaya: "Wilaya",
    runs: "Période",
    age: "Âge",
    type: "Type",
    mark: "Note",
    average: "Moyenne",
    percent: "Pourcentage",
    action: "Action",
    onWhat: "Sur quoi",
  },

  filters: {
    status: "Statut",
    search: "Rechercher",
    role: "Rôle",
    course: "Formation",
    student: "Stagiaire",
    day: "Jour",
    method: "Mode",
    who: "Qui",
    from: "Du",
    to: "Au",
    category: "Catégorie",
    condition: "État",
    location: "Salle",
    month: "Mois",
    year: "Année",
  },

  dashboard: {
    title: "Tableau de bord",
    morning: "Bonjour",
    afternoon: "Bon après-midi",
    evening: "Bonsoir",
    errorTitle: "Impossible de charger le tableau de bord",
    errorBody:
      "Les chiffres ne sont pas revenus du serveur. Une actualisation suffit généralement.",
    blurbOwner: "Voici ce qui se passe aujourd'hui à SM Academy.",
    blurbAdmin: "L'activité de l'établissement.",
    blurbReception:
      "La journée à l'accueil — inscriptions, paiements et file de validation.",
    blurbProfessor: "Ce qui vient, et ce qui reste à corriger.",
    blurbStudent: "Vos formations, vos notes et vos paiements au même endroit.",
    attention: "Demande une attention",
    attentionNote: "En attente d'une personne, pas d'une échéance.",
    awaitingApproval: "En attente de validation",
    awaitingApprovalNote: "Encaissé, pas encore validé",
    unmarked: "Évaluations non corrigées",
    unmarkedNote: "Aucune note saisie",
    toModerate: "Avis à modérer",
    toModerateNote: "En attente d'une décision",
    money: "Argent",
    moneyNote:
      "Paiements validés uniquement. L'argent en attente n'est pas encore une recette.",
    collected: "Encaissé ce mois-ci",
    collectedNote: "{total} depuis le début",
    outstanding: "Reste à recouvrer",
    outstandingNote: "Contracté moins validé, sur les inscriptions en cours",
    teaching: "Enseignement",
    activeCourses: "Formations actives",
    liveEnrollments: "Inscriptions en cours",
    myCourses: "Mes formations",
    yourCourses: "Vos formations",
    myStudents: "Mes stagiaires",
    people: "Personnes",
    activeStudents: "Stagiaires actifs",
    professors: "Formateurs",
    reception: "Accueil",
    administrators: "Administrateurs",
    today: "Aujourd'hui",
    enrollmentsToday: "Inscriptions du jour",
    paymentsToday: "Paiements enregistrés aujourd'hui",
    nextClass: "Prochain cours",
    openClass: "Ouvrir le cours",
    enrolledCount: "{count} inscrits",
    yourBalance: "Votre solde",
    stillToPay: "Reste à payer",
    allPaidUp: "Rien à régler. Vous êtes à jour.",
    settled: "Soldé",
    agreed: "Convenu",
    paid: "Payé",
    remaining: "Reste",
    paidOfTotal: "{paid} payés sur {total}",
    quickActions: "Actions rapides",
    recordPayment: "Enregistrer un paiement",
    enrolStudent: "Inscrire un stagiaire",
    addPerson: "Ajouter une personne",
    reviewPending: "Examiner les paiements en attente",
    enterMarks: "Saisir des notes",
    runReport: "Lancer un rapport",
    yourTimetable: "Votre planning",
    yourMarks: "Vos notes",
  },

  users: {
    title: "Personnes",
    lede: "Les comptes sont désactivés, jamais supprimés — les inscriptions, les paiements et les notes doivent rester rattachés à quelqu'un.",
    ledeSelf:
      "Les informations que nous détenons sur vous. Demandez à l'accueil de corriger ce qui serait inexact.",
    errorTitle: "Impossible de charger les personnes",
    searchPlaceholder: "Nom, identifiant ou téléphone",
    newPerson: "Nouvelle personne",
    newPersonLede:
      "Il n'y a pas d'inscription publique — chaque compte est créé ici par le personnel, et les rôles que vous pouvez attribuer sont bornés par les vôtres.",
    emptyTitle: "Personne ne correspond à ces filtres",
    emptyBody:
      "Les comptes hors de votre portée ne sont pas listés du tout — la recherche ne couvre que les personnes que votre rôle peut voir.",
    lastSeen: "Vu pour la dernière fois",
    studentRecord: "Dossier stagiaire",
    professorRecord: "Dossier formateur",
    dateOfBirth: "Date de naissance",
    priorLevel: "Niveau antérieur",
    emergencyContact: "Contact d'urgence",
    emergencyPhone: "Téléphone d'urgence",
    staffNotes: "Notes internes",
    specialisation: "Spécialité",
    hourlyRate: "Taux horaire",
    qualifications: "Diplômes",
    hiredOn: "Recruté le",
    address: "Adresse",
    wilaya: "Wilaya",
    notGiven: "Non renseigné",
    notAssessed: "Non évalué",
    whoTheyAre: "Identité",
    contactHint:
      "Un numéro de téléphone ou une adresse e-mail sert à les joindre ; l'identifiant sert à se connecter.",
    role: "Rôle",
    chooseRole: "Choisissez un rôle",
    roleHint:
      "Détermine le tableau de bord d'arrivée, et les champs ci-dessous qui s'appliquent.",
    firstName: "Prénom",
    lastName: "Nom",
    phone: "Téléphone",
    phoneHint: "Enregistré au format international. 0555 12 34 56 convient.",
    email: "E-mail",
    optionalLater:
      "Tout ce qui suit est facultatif et peut être complété plus tard.",
    dobHint: "L'âge en est déduit, il n'est pas stocké.",
    createAccount: "Créer le compte",
    accountCreated: "Compte créé",
    roles: "Rôles",
    rolesNote:
      "Un rôle est un ensemble de permissions, pas une étiquette. Le rôle principal détermine le tableau de bord d'arrivée.",
    grantRole: "Accorder {role}",
    revokeRole: "Retirer {role}",
    roleGranted: "{role} accordé",
    roleRevoked: "{role} retiré",
    accountStatus: "État du compte",
    accountStatusNote:
      "Les comptes sont désactivés, jamais supprimés — leurs inscriptions, paiements et notes restent rattachables.",
    reason: "Motif",
    reasonPlaceholder: "A quitté l'établissement à la fin du trimestre.",
    reasonNote: "Consigné dans le journal d'audit avec l'auteur du changement.",
    reactivate: "Réactiver",
    suspend: "Suspendre",
    deactivate: "Désactiver",
    cannotChangeStatus: "Votre rôle ne permet pas de changer l'état de ce compte.",
    reactivated: "Compte réactivé",
    reactivatedNote: "La personne pourra se reconnecter.",
    suspended: "Compte suspendu",
    deactivated: "Compte désactivé",
    deactivatedNote:
      "La personne est déconnectée à sa prochaine requête et ne peut plus se reconnecter. Ses enregistrements restent exactement là où ils sont.",
    resetPasswordTitle: "Réinitialiser ce mot de passe ?",
    resetPassword: "Réinitialiser le mot de passe",
    resetPasswordNote:
      "Toutes ses sessions ouvertes cessent immédiatement de fonctionner, et le nouveau mot de passe vous est montré une seule fois.",
    newPasswordOnce:
      "Transmettez-le maintenant. Il ne sera plus affiché.",
    primary: "principal",
  },

  courses: {
    title: "Formations",
    lede: "Le catalogue. Une formation porte son propre tarif, et chaque inscription fige le tarif en vigueur au moment où elle est faite — modifier un tarif ici ne réécrit donc jamais les factures du trimestre passé.",
    errorTitle: "Impossible de charger les formations",
    searchPlaceholder: "Intitulé ou identifiant",
    emptyTitle: "Aucune formation ne correspond à ces filtres",
    emptyBody: "Effacez les filtres pour voir tout le catalogue.",
    taughtBy: "Assurée par",
    unassigned: "Non attribuée",
    price: "Tarif",
    priceNote: "Figé sur chaque inscription au moment où elle est faite",
    seats: "Places",
    uncapped: "Sans limite",
    weeklySchedule: "Planning hebdomadaire",
    weeklyScheduleNote:
      "Un rythme récurrent, pas un agenda de séances datées.",
    fullTimetable: "Planning complet",
    assessments: "Évaluations",
    assessmentsNote:
      "Chacune porte un coefficient, c'est-à-dire sa part dans la moyenne.",
    noAssessments: "Aucune évaluation",
    noAssessmentsBody:
      "Les notes et les moyennes apparaissent ici dès qu'une évaluation existe sur cette formation.",
    onlyPublished: "Seules les évaluations publiées affichent une note.",
    yourEnrollment: "Votre inscription",
    gradebook: "Relevé de notes",
    yourMarks: "Vos notes",
    published: "Publiée",
    notPublished: "Non publiée",
  },

  enrollments: {
    title: "Inscriptions",
    titleSelf: "Vos inscriptions",
    lede: "Une ligne par stagiaire et par formation, avec le tarif convenu à ce moment-là. Les paiements et les notes en dépendent, d'où le fait qu'elles soient annulées plutôt que supprimées.",
    errorTitle: "Impossible de charger les inscriptions",
    emptyTitle: "Aucune inscription ne correspond à ces filtres",
    emptyBody:
      "Une inscription, c'est un stagiaire sur une formation. Effacez les filtres pour toutes les voir.",
    agreedPrice: "Tarif convenu",
    enrolled: "Inscrit le",
    enrolOne: "Inscrire un stagiaire",
    enrolLede:
      "Un stagiaire, une formation. Tout le reste — paiements, notes, avis — dépend de l'inscription créée ici.",
    detailTitle: "Inscription",
    detailLede:
      "Un stagiaire, une formation — et tout ce qui s'y rattache.",
    course: "Formation",
    profile: "Profil",
    priceAgreed: "Tarif convenu à l'inscription",
    student: "Stagiaire",
    chooseStudent: "Choisissez un stagiaire",
    chooseStudentHint: "Comptes stagiaires actifs uniquement.",
    chooseCourse: "Choisissez une formation",
    chooseCourseHint:
      "Les formations en brouillon et actives acceptent les inscriptions.",
    notes: "Notes",
    notesPlaceholder: "Paiement en trois fois ; frère ou sœur de STU-000004.",
    notesHint: "La personne est notifiée, et l'inscription démarre active.",
    whatWillBeRecorded: "Ce qui sera enregistré",
    courseRuns: "La formation se déroule",
    priceFrozen: "Tarif, figé à l'inscription",
    submit: "Inscrire",
    done: "Inscrit",
    balance: "Solde",
    balanceNote: "Calculé à chaque lecture depuis les paiements, jamais stocké.",
    frozenAtEnrollment: "Figé à l'inscription",
    approvedPayments: "Paiements validés",
    awaitingApproval: "En attente de validation",
    notCountedAsPaid: "Non comptés comme payés",
    remaining: "Reste",
    stillOwed: "Encore dû",
    outstanding: "À recouvrer",
    payments: "Paiements",
    paymentsNote:
      "Chaque écriture est enregistrée d'abord, puis validée par quelqu'un d'autre.",
    paymentsFor: "Paiements de cette inscription",
    noPayments: "Rien d'enregistré sur cette inscription",
    noPaymentsBody:
      "Espèces reçues au guichet, virement ou chèque — chacun est enregistré ici puis validé.",
    reference: "Référence",
  },

  grades: {
    title: "Notes",
    lede: "Les moyennes sont recalculées depuis les notes brutes à chaque consultation, jamais stockées. Changez le coefficient d'une évaluation et toutes les moyennes suivent.",
    scopeNote:
      "Le relevé se limite aux formations qui vous sont attribuées.",
    noCourses: "Aucune formation ne vous est attribuée",
    noCoursesBody:
      "Un relevé apparaîtra ici dès qu'une formation vous sera attribuée.",
    chooseCourse: "Choisissez une formation",
    chooseCourseBody:
      "Sélectionnez-en une ci-dessus pour voir son relevé et ses feuilles de notes.",
    markSheets: "Feuilles de notes",
    markSheetsNote: "Ouvrez-en une pour saisir ou corriger des notes.",
    noAssessments: "Aucune évaluation sur cette formation",
    noAssessmentsBody:
      "Les notes se saisissent sur une évaluation : il faut donc qu'il en existe une avant la feuille.",
    gradebook: "Relevé de notes",
    nobodyEnrolled: "Personne n'est encore inscrit à cette formation",
    nobodyEnrolledBody:
      "Le relevé se remplit à mesure que les stagiaires s'inscrivent et que les évaluations sont corrigées.",
    notMarkedYet: "Pas encore noté",
    yourMarks: "Vos notes",
    yourMarksLede:
      "Résultats publiés uniquement. Une note apparaît ici lorsque votre formateur publie l'évaluation à laquelle elle appartient.",
    noMarks: "Aucune note publiée",
    noMarksBody:
      "Votre formateur publie une évaluation quand la classe est corrigée. Rien ne vous est caché ici — il n'y a simplement rien encore.",
    corrected: "Corrigée",
    assessment: "Évaluation",
    recorded: "Saisie le",
    markSheet: "Feuille de notes",
    outOf: "Sur",
    weight: "Coefficient",
    weightNote: "Sa part dans la moyenne de la formation",
    marked: "Notés",
    heldOn: "Passée le",
    published: "Publiée",
    notPublished: "Non publiée",
    student: "Stagiaire",
    comment: "Commentaire",
    history: "Historique",
    notMarked: "Non noté",
    saveSheet: "Enregistrer la feuille",
    enterMoves: "Entrée ou flèche bas passe au stagiaire suivant.",
    atomicNote:
      "La feuille s'enregistre d'un bloc : soit toutes les notes passent, soit aucune.",
    sheetSaved: "Feuille enregistrée",
    publishTitle: "Publier ces notes ?",
    publishAction: "Publier les notes",
    publishBody:
      "Chaque stagiaire noté est notifié. C'est irréversible — une note erronée se corrige, elle ne se masque pas.",
    notPublishedNote:
      "Les stagiaires ne voient pas encore ces notes. La publication notifie tous ceux qui en ont une.",
    publishedNote: "Tous les stagiaires de la liste ont une note.",
    marksPublished: "Notes publiées",
    marksPublishedNote: "Tous ceux qui ont une note ont été notifiés.",
  },

  payments: {
    title: "Paiements",
    lede: "Chaque écriture est enregistrée, puis validée par quelqu'un d'autre. Rien n'est modifié ni supprimé ici — une erreur avant validation s'annule, une erreur après se corrige par une nouvelle écriture.",
    errorTitle: "Impossible de charger les paiements",
    emptyTitle: "Aucun paiement ne correspond à ces filtres",
    emptyBody: "Effacez les filtres pour voir toutes les écritures.",
    reference: "Référence",
    noReferenceNote:
      "Les espèces reçues au guichet n'en ont normalement aucune.",
    recordedDecided: "Enregistré / décidé",
    amount: "Montant",
    student: "Stagiaire",
    course: "Formation",
    currency: "Devise",
    method: "Mode",
    paidOn: "Payé le",
    recordTitle: "Enregistrer un paiement",
    recordLede:
      "De l'argent reçu, rattaché à l'inscription à laquelle il appartient. Chaque écriture démarre en attente et est validée par quelqu'un d'autre — vous ne pouvez pas valider celle que vous avez saisie.",
    enrollment: "Inscription",
    chooseEnrollment: "Choisissez un stagiaire et une formation",
    chooseEnrollmentHint:
      "Inscriptions actives uniquement. Un paiement sur une inscription retirée exige d'abord une inscription en cours.",
    amountHint: "La somme remise, en unités entières ou avec les centimes.",
    amountPlaceholder: "20000",
    paidOnHint:
      "Le jour où l'argent est arrivé, et non la date du jour si elles diffèrent.",
    methodHint: "Comment il a été réglé",
    notes: "Notes",
    notesPlaceholder: "Deuxième versement ; reçu numéro 41.",
    against: "Rattaché à",
    loadingBalance: "Chargement du solde…",
    agreed: "Convenu",
    paid: "Payé",
    pending: "En attente",
    remaining: "Reste",
    attachLater:
      "Le bordereau se joint sur la page du paiement, une fois celui-ci créé.",
    submit: "Enregistrer le paiement",
    recorded: "Paiement enregistré",
    pendingNoticeSelf:
      "Cette écriture sera en attente. Vous ne pourrez pas la valider vous-même — celui qui enregistre un paiement ne peut pas être celui qui confirme sa réception.",
    pendingNotice:
      "Cette écriture restera en attente jusqu'à ce qu'une personne habilitée la confirme. L'accueil encaisse ; il ne valide pas.",
    amountInvalid: "Saisissez un montant, par exemple 20000 ou 20000.50.",
    amountTooSmall: "Un montant doit être supérieur à zéro.",
    details: "Détail",
    history: "Historique",
    proof: "Justificatif",
    decision: "Décision",
    decisionNote: "Enregistré par une personne, confirmé par une autre.",
    notRecorder: "Pas la personne qui l'a enregistré",
    selfApproveBlocked:
      "Vous avez enregistré ce paiement. Quelqu'un d'autre doit le valider.",
    statePending:
      "Enregistré, pas encore validé. Ce montant n'est pas compté comme payé.",
    stateApproved: "Validé et décompté du solde.",
    stateRejected: "Refusé. Rien n'a été décompté.",
    stateCancelled: "Annulé avant toute décision.",
    reasonForRejection: "Motif du refus",
    approveTitle: "Valider ce paiement ?",
    approveAction: "Valider le paiement",
    approveBody:
      "Cela décompte l'argent du solde et ne peut pas être annulé.",
    approve: "Valider",
    rejectTitle: "Refuser ce paiement ?",
    rejectAction: "Refuser le paiement",
    rejectBody: "L'écriture reste au registre avec le motif attaché.",
    reject: "Refuser",
    rejectWhy: "Pourquoi ce refus ?",
    rejectWhyHint: "La personne refusée doit pouvoir en connaître la raison.",
    cancelTitle: "Annuler cette écriture ?",
    cancelAction: "Annuler l'écriture",
    cancelBody:
      "Pour une écriture qui n'aurait pas dû être faite. Elle reste au registre, close.",
    cancelWhy: "Pourquoi cette annulation ?",
    cancelWhyPlaceholder: "Enregistré sur la mauvaise inscription.",
    reasonShown:
      "Consigné avec le paiement et visible par quiconque le consulte.",
    approved: "Paiement validé",
    rejected: "Paiement refusé",
    cancelled: "Écriture annulée",
    noProof: "Aucun justificatif joint.",
    proofAttached: "Justificatif joint",
    proofScanNote: "Il est analysé avant que quiconque puisse l'ouvrir.",
    scanning:
      "Analyse en cours. Un fichier n'est pas remis avant d'avoir été analysé.",
    scanned: "Analysé",
    uploading: "Envoi…",
    attachProof: "Joindre un justificatif",
    downloadFailed: "Impossible de préparer le téléchargement.",
    storageRefused: "Le fichier a été refusé par le service de stockage.",
    uploadIncomplete: "L'envoi ne s'est pas terminé.",
  },

  reviews: {
    title: "Avis",
    lede: "Rédigés par les stagiaires ayant terminé une formation. Rien n'est supprimé — masquer ou refuser conserve la ligne, la décision et son auteur.",
    ledeProfessor:
      "Ce que les stagiaires ont dit des formations que vous pouvez voir. Avis validés uniquement, et jamais avec le nom de l'auteur pour un formateur.",
    errorTitle: "Impossible de charger les avis",
    byCourse: "Par formation",
    byCourseNote:
      "Avis validés uniquement, calculé à la lecture. Une moyenne stockée ne pourrait plus être recalculée une fois un avis masqué.",
    awaitingModeration: "En attente de modération",
    nothingToModerate: "Rien à modérer",
    caughtUp:
      "Vous êtes à jour. De nouveaux avis arriveront à mesure que les stagiaires terminent leurs formations.",
    emptyTitle: "Aucun avis pour l'instant",
    noComment: "Aucun commentaire laissé.",
    anonymous: "Anonyme",
    replyFromInstitute: "Réponse de l'établissement",
    publicReply: "Réponse publique",
    publicReplyNote: "Publiée avec l'avis si vous le validez.",
    moderate: "Modérer",
    changeDecision: "Changer la décision",
    approve: "Valider",
    reject: "Refuser",
    rejectTitle: "Refuser cet avis ?",
    rejectAction: "Refuser l'avis",
    rejectBody:
      "Il reste au dossier avec votre décision, et n'apparaît jamais publiquement.",
    approved: "Avis validé",
    hidden: "Avis masqué",
    rejected: "Avis refusé",
    keptNote: "La ligne, la décision et son auteur sont tous conservés.",
    writeTitle: "Donner un avis",
    writeNote: "Votre formateur ne saura jamais qui l'a écrit.",
    rating: "Note",
    comment: "Commentaire",
    commentPlaceholder: "Ce qui était bien, ce qui pourrait être mieux.",
    submit: "Envoyer l'avis",
    submitted: "Avis envoyé",
  },

  schedules: {
    title: "Planning",
    lede: "Un rythme hebdomadaire récurrent, pas un agenda de séances datées. Chaque créneau se répète chaque semaine entre ses dates d'effet.",
    errorTitle: "Impossible de charger le planning",
    emptyTitle: "Aucun cours programmé",
    emptyBody:
      "Votre planning hebdomadaire apparaîtra ici dès qu'une formation vous sera attribuée.",
    session: "Cours",
  },

  reports: {
    title: "Rapports",
    lede: "Chaque chiffre est lu depuis les lignes à chaque requête — rien n'est mis en cache, rien n'est stocké, de sorte que les totaux se rapprochent du registre par construction.",
    noneForRole: "Aucun rapport pour votre rôle",
    noneForRoleBody:
      "Consulter un rapport est une permission à part entière, accordée séparément des écrans dont les chiffres proviennent.",
    errorTitle: "Impossible d'exécuter ce rapport",
    errorBody:
      "La requête n'est pas revenue. Resserrer la période et réessayer suffit généralement.",
    totals: "Totaux",
    rows: "Lignes",
    emptyTitle: "Rien ne correspond à ces filtres",
    emptyBody:
      "Élargissez la période, ou effacez la formation, pour voir plus de lignes.",
    enrollmentsTitle: "Inscriptions",
    enrollmentsNote:
      "Effectif par formation, par statut. Aucun montant n'y figure.",
    revenueTitle: "Recettes",
    revenueNote:
      "Argent réellement encaissé, par formation. Paiements validés uniquement.",
    outstandingTitle: "Reste à recouvrer",
    outstandingNote: "Ce que chaque inscription en cours doit encore.",
    unsettledOnly: "Non soldées uniquement",
    export: "Exporter",
    exportNote:
      "Un CSV reprenant exactement les lignes ci-dessus, construit en arrière-plan.",
    exportBuilding: "Construction du fichier…",
    exportDownload: "Télécharger",
    exportNothingQueued: "Rien en file pour l'instant.",
    exportPrivate: "Privé",
    exportTooLong: "L'export prend plus de temps que prévu. Revenez plus tard.",
    exportReady: "Export prêt",
    exportLost: "Export perdu de vue. Rechargez pour voir son état.",
    exportAgain: "Exporter à nouveau",
    exportCsv: "Exporter en CSV",
    exportFailed: "L'export a échoué.",
  },

  audit: {
    title: "Journal d'audit",
    lede: "En ajout seul, garanti par la base de données plutôt que par convention — aucun point d'accès ne modifie ni ne supprime une ligne, à aucune version, et les actions qui méritent le plus d'y figurer sont justement celles qu'on voudrait effacer.",
    errorTitle: "Impossible de lire le journal",
    emptyTitle: "Rien d'enregistré pour ces filtres",
    emptyBody:
      "Le journal contient chaque action conséquente. S'il est vide, c'est qu'aucune ne correspond — pas qu'aucune n'a eu lieu.",
    loadMore: "Charger la suite",
    endOfTrail: "C'est toute la trace.",
    loadMoreFailed: "Impossible de charger la suite.",
    actions: {
      loginFailed: "Échec de connexion",
      userCreated: "Compte créé",
      userUpdated: "Compte modifié",
      userStatusChanged: "État du compte changé",
      passwordReset: "Mot de passe réinitialisé",
      roleGranted: "Rôle accordé",
      roleRevoked: "Rôle retiré",
      studentEnrolled: "Stagiaire inscrit",
      markChanged: "Note modifiée",
      marksPublished: "Notes publiées",
      paymentRecorded: "Paiement enregistré",
      paymentApproved: "Paiement validé",
      paymentRejected: "Paiement refusé",
      proofDownloaded: "Justificatif téléchargé",
      reviewModerated: "Avis modéré",
      reportExported: "Rapport exporté",
      exportDownloaded: "Export téléchargé",
    },
    subjects: {
      enrollment: "Une inscription",
      reportExport: "Un export",
      person: "Une personne",
      payment: "Un paiement",
      course: "Une formation",
      review: "Un avis",
    },
  },

  notifications: {
    title: "Notifications",
    lede: "Adressées à vous et à personne d'autre — une inscription faite en votre nom, une note publiée, un paiement décidé.",
    errorTitle: "Impossible de charger les notifications",
    unreadOnly: "Non lues",
    markAllRead: "Tout marquer comme lu",
    allMarkedRead: "Tout marqué comme lu",
    nothingUnread: "Rien de non lu",
    caughtUp: "Vous êtes à jour.",
    all: "Toutes",
    emptyTitle: "Aucune notification",
    emptyBody:
      "Vous serez informé de ce qui vous concerne — une inscription, une note publiée, un paiement décidé.",
  },

  account: {
    title: "Votre compte",
    lede: "Ce que nous détenons sur vous, et ce que votre rôle vous permet d'atteindre.",
    fullRecord: "Dossier complet",
    lastSignedIn: "Dernière connexion",
    permissionsTitle: "Ce que votre rôle permet",
    permissionsNote:
      "Accordé par permission, pas par intitulé de poste. Le serveur vérifie chacune d'elles à chaque requête.",
    password: "Mot de passe",
    passwordNote:
      "Changé ici, par vous. Personne ne peut lire l'actuel — il n'a jamais été stocké sous une forme lisible.",
    current: "Mot de passe actuel",
    newPassword: "Nouveau mot de passe",
    newPasswordHint:
      "Long vaut mieux que compliqué. Une phrase dont vous vous souvenez est plus solide qu'un mot avec des symboles.",
    repeat: "Répétez le nouveau mot de passe",
    submit: "Changer le mot de passe",
    changed: "Mot de passe changé",
    changedNote: "Utilisez le nouveau à votre prochaine connexion.",
    mismatch: "Les deux ne correspondent pas.",
    correctionNote:
      "Quelque chose est inexact ? Demandez à l'accueil de le corriger — les modifications d'un dossier se font en un seul endroit, là où elles sont consignées.",
    sessionNote:
      "Changer votre mot de passe ne vous déconnecte pas de ce navigateur. Si vous pensez que quelqu'un d'autre utilise votre compte, prévenez un administrateur.",
  },


  // ----------------------------------------------------------- logistics --

  // --------------------------------------------------------------- print --

  // ---------------------------------------------------------- attendance --

  // ------------------------------------------------------------ settings --
  settings: {
    title: "Paramètres",
    lede: "Les coordonnées de l'établissement. Elles ouvrent chaque document imprimé : ce qui est ici est ce qui figure sur un reçu remis à un parent.",
    errorTitle: "Les paramètres n'ont pas pu être chargés",
    identity: "Identité",
    identityLede: "Le nom sur l'enseigne, et la raison sociale si elle diffère.",
    contact: "Adresse et contact",
    contactLede: "Imprimés sous le nom sur chaque rapport. Ce qui est laissé vide est simplement omis.",
    documents: "Documents imprimés",
    documentsLede: "Ce qui apparaît en bas de chaque page, à côté du numéro.",
    name: "Nom de l'établissement",
    legalName: "Raison sociale",
    addressLine: "Adresse",
    city: "Commune",
    wilaya: "Wilaya",
    phone: "Téléphone",
    email: "E-mail",
    website: "Site web",
    registrationNumber: "Numéro d'enregistrement",
    tagline: "Slogan",
    printFooter: "Pied de page",
    saved: "Paramètres enregistrés",
    readOnly: "Ces coordonnées sont gérées par le propriétaire. Vous pouvez voir ce qui figure sur les documents imprimés, sans le modifier.",
    logoNote: "Le logo est l'artwork officiel intégré à l'application et ne se modifie pas ici — une seconde copie téléversée par un formulaire, c'est ainsi qu'un établissement se retrouve avec deux logos et aucune réponse sur lequel fait foi.",
    previewTitle: "En-tête des documents",
  },
  attendance: {
    title: "Présences",
    lede: "Une feuille par classe et par jour. Une feuille que personne n'a faite est vide, ce qui n'est pas la même chose que tout le monde absent.",
    errorTitle: "Les présences n'ont pas pu être chargées",
    emptyTitle: "Aucune feuille de présence",
    emptyBody: "Ouvrez-en une pour une classe et une date, et toute la liste apparaît prête à pointer.",
    openRegister: "Ouvrir une feuille",
    openRegisterLede: "Choisissez la classe et le jour. Si quelqu'un l'a déjà ouverte, vous serez conduit à la sienne plutôt que d'en créer une seconde.",
    takeRegister: "Faire l'appel",
    saveRegister: "Enregistrer l'appel",
    saved: "Appel enregistré",
    savedDetail: "{created} pointés, {updated} corrigés.",
    heldOn: "Date",
    classLabel: "Classe",
    topic: "Sujet",
    topicHint: "Ce qui a été traité, si cela mérite d'être noté.",
    room: "Salle",
    marked: "Pointés",
    roster: "Inscrits",
    present: "Présents",
    absent: "Absents",
    late: "En retard",
    rate: "Taux",
    minutesLate: "Minutes de retard",
    note: "Remarque",
    markAllPresent: "Tout le monde présent",
    clearAll: "Tout effacer",
    corrected: "Corrigé",
    correctedNote: "Ce pointage a été modifié après la première saisie.",
    summary: "Synthèse des présences",
    summaryLede: "Taux sur la période, par stagiaire. Un retard compte comme une présence.",
    noRate: "Aucun appel fait",
    notOnRoster: "Personne n'est encore inscrit à cette classe.",
    readOnly: "Vous pouvez consulter les présences et les imprimer. Faire l'appel revient au formateur de la classe.",
    printRegister: "Imprimer la feuille",
    printSummary: "Imprimer le rapport de présence",
    blankSheet: "Une feuille qui n'a pas été faite s'imprime vierge, prête à être remplie à la main.",
  },
  print: {
    print: "Imprimer",
    printThis: "Imprimer cette liste",
    savePdf: "Enregistrer en PDF",
    preview: "Aperçu avant impression",
    generated: "Généré le",
    pageOf: "Page {page} sur {total}",
    dialogHint: "La fenêtre d'impression s'ouvre d'elle-même. La destination « Enregistrer en PDF » de votre navigateur produit le même document sous forme de fichier.",
    nothingToPrint: "Il n'y a rien à imprimer pour cette sélection.",
    truncated: "Ce document montre les 2 000 premiers enregistrements d'une sélection plus large. Affinez les filtres pour imprimer le reste.",
    filteredNotice: "Ceci est une sélection filtrée, pas la liste complète.",
    openInNewTab: "Ouvre une feuille A4 imprimable dans un nouvel onglet.",
    studentList: "LISTE DES STAGIAIRES",
    staffList: "LISTE DU PERSONNEL",
    studentProfile: "FICHE STAGIAIRE",
    courseList: "LISTE DES FORMATIONS",
    classList: "LISTE DE CLASSE",
    enrollmentList: "LISTE DES INSCRIPTIONS",
    scheduleTitle: "EMPLOI DU TEMPS",
    incomeReport: "RAPPORT DES RECETTES",
    receiptTitle: "REÇU DE PAIEMENT",
    financialSummary: "SYNTHÈSE FINANCIÈRE",
    attendanceRegister: "FEUILLE DE PRÉSENCE",
    attendanceReport: "RAPPORT DE PRÉSENCE",
    managementReport: "RAPPORT DE GESTION",
    gradebookTitle: "RELEVÉ DE NOTES",
    totalStudents: "Total stagiaires",
    totalStaff: "Total personnel",
    totalCourses: "Total formations",
    totalEnrollments: "Total inscriptions",
    totalRecords: "Total enregistrements",
    totalIncome: "Total des recettes",
    totalExpenses: "Total des dépenses",
    netBalance: "Solde net",
    outstanding: "Restant dû",
    attendanceRate: "Taux de présence",
    preparedBy: "Établi par",
    signature: "Signature",
    receivedBy: "Reçu par",
    period: "Période",
    allTime: "Depuis le début",
    receiptNumber: "Numéro de reçu",
    amountPaid: "Montant réglé",
    remainingBalance: "Solde restant",
    payer: "Reçu de",
    forCourse: "Pour",
    pendingNotice: "Ce reçu correspond à un paiement encore en attente d'approbation.",
    incomeByCourse: "Recettes par formation",
    expensesByCategory: "Dépenses par catégorie",
    monthByMonth: "Mois par mois",
    income: "Recettes",
    expenditure: "Dépenses",
    net: "Net",
    people: "Personnes",
    teaching: "Enseignement",
    money: "Finances",
    inventory: "Inventaire",
    newRegistrations: "Nouvelles inscriptions",
    activeStudents: "Stagiaires actifs",
    activeCourses: "Formations actives",
    liveEnrollments: "Inscriptions en cours",
    registersTaken: "Appels effectués",
    pendingPayments: "Paiements en attente",
    itemsNeedingRepair: "Articles à réparer",
    itemsDamaged: "Articles endommagés",
    itemsMissing: "Articles manquants",
    inventoryLines: "Lignes d'inventaire",
    inventoryUnits: "Articles au total",
    registered: "Inscrit le",
    date: "Date",
    time: "Horaire",
    entries: "Écritures",
    balance: "Solde",
    notes: "Remarques",
    status: "Statut",
    summary: "Synthèse",
  },
  logistics: {
    title: "Logistique",
    lede: "Ce que l'académie possède, et ce qu'il en coûte de garder les portes ouvertes. Inventaire et dépenses mensuelles au même endroit.",
    inventory: "Inventaire",
    expensesTab: "Dépenses",
    historyTab: "Historique mensuel",
    setupTab: "Catégories et salles",
    readOnly: "Vous pouvez tout consulter ici et l'imprimer. L'ajout, la modification et la suppression reviennent au propriétaire ou à un administrateur.",
    errorTitle: "L'inventaire n'a pas pu être chargé",
    emptyTitle: "Rien dans l'inventaire pour l'instant",
    emptyBody: "Enregistrez les chaises, les tables, les machines et le matériel de l'académie. Chaque article peut être compté, localisé et imprimé.",
    addItem: "Ajouter un article",
    editItem: "Modifier l'article",
    itemLede: "Une ligne de l'inventaire. Les objets identiques sont comptés ensemble ; tout ce qui porte un numéro de série a sa propre ligne.",
    addItemLede: "Les catégories et les salles se gèrent dans l'onglet de configuration : un nouveau type de matériel ne demande jamais de développeur.",
    name: "Nom de l'article",
    category: "Catégorie",
    quantity: "Quantité",
    condition: "État",
    status: "Statut",
    location: "Emplacement / salle",
    purchaseDate: "Date d'achat",
    purchasePrice: "Prix d'achat",
    serial: "Numéro de série",
    notes: "Remarques",
    lastUpdated: "Dernière mise à jour",
    added: "Ajouté",
    reference: "Reçu ou référence",
    method: "Mode de paiement",
    amount: "Montant",
    spentOn: "Date de paiement",
    accountingMonth: "Mois comptable",
    description: "Description",
    quantityHint: "Combien de cet article exactement. Jamais négatif.",
    serialHint: "Pour les machines. Deux articles ne peuvent pas partager un numéro de série.",
    priceHint: "Ce qu'il a coûté, si on le sait. Laissez vide sinon.",
    accountingMonthHint: "Le mois auquel la dépense se rattache. Suit la date de paiement — à changer quand la facture de février est réglée en mars.",
    noCategories: "Aucune catégorie. Ajoutez-en une dans l'onglet de configuration.",
    noLocations: "Aucune salle enregistrée. Un article peut être classé sans.",
    totalItems: "Lignes d'inventaire",
    totalUnits: "Articles au total",
    totalUnitsNote: "En comptant les quantités, pas les lignes.",
    needingRepair: "À réparer",
    damaged: "Endommagés",
    missing: "Manquants",
    underRepair: "En réparation",
    available: "Disponibles",
    inUse: "En service",
    categoriesCount: "Catégories",
    roomsCount: "Salles",
    byCategory: "Par catégorie",
    byLocation: "Par salle",
    byCondition: "Par état",
    recentlyAdded: "Ajoutés récemment",
    lines: "lignes",
    expensesTitle: "Dépenses mensuelles",
    expensesLede: "Ce que l'institut a dépensé, classé par mois de rattachement plutôt que par jour de paiement.",
    expensesErrorTitle: "Les dépenses n'ont pas pu être chargées",
    expensesEmptyTitle: "Rien d'enregistré pour ce mois",
    expensesEmptyBody: "Électricité, eau, internet, réparations, nettoyage — tout ce que l'institut a payé a sa place ici.",
    addExpense: "Ajouter une dépense",
    editExpense: "Modifier la dépense",
    addExpenseLede: "Une chose que l'institut a payée. Le total du mois est calculé par le serveur, jamais par cet écran.",
    monthTotal: "Ce mois-ci",
    previousMonth: "Mois précédent",
    yearTotal: "Cumul de l'année",
    entriesThisMonth: "Écritures ce mois-ci",
    upOn: "{amount} de plus qu'en {month}",
    downOn: "{amount} de moins qu'en {month}",
    sameAs: "Identique à {month}",
    firstMonth: "Rien n'a été enregistré en {month}.",
    breakdown: "Par catégorie",
    monthlyTotals: "Mois par mois",
    historyTitle: "Historique mensuel",
    historyLede: "Chaque mois où quelque chose a été enregistré, du plus récent au plus ancien. Ouvrez-en un pour lire ses écritures.",
    historyEmptyTitle: "Aucun mois enregistré",
    historyEmptyBody: "Dès que des dépenses sont saisies, chaque mois apparaît ici avec son total et sa catégorie la plus lourde.",
    monthColumn: "Mois",
    totalColumn: "Total des dépenses",
    mainCategory: "Catégorie principale",
    entries: "Écritures",
    viewMonth: "Voir",
    setupTitle: "Catégories et salles",
    setupLede: "Les libellés sous lesquels cette section classe les choses. Ce sont des données, pas du code — un nouveau type de matériel s'ajoute ici.",
    itemCategories: "Catégories d'articles",
    expenseCategories: "Catégories de dépenses",
    rooms: "Salles et réserves",
    addCategory: "Ajouter une catégorie",
    addRoom: "Ajouter une salle",
    newCategoryPlaceholder: "Imprimantes 3D",
    newRoomPlaceholder: "Salle 3",
    retire: "Retirer",
    restore: "Rétablir",
    retired: "Retiré",
    retiredNote: "Un libellé retiré disparaît des listes déroulantes. Tout ce qui y est déjà classé garde son nom.",
    filedUnder: "{count} classés ici",
    nothingFiled: "Rien n'est encore classé ici",
    print: "Imprimer",
    printInventory: "Imprimer la liste logistique",
    printExpenses: "Imprimer les dépenses du mois",
    printNow: "Imprimer",
    printHint: "Ouvre une feuille A4 imprimable dans un nouvel onglet.",
    printingDialog: "La fenêtre d'impression s'ouvre d'elle-même. Fermez cet onglet une fois terminé.",
    documentTitle: "INVENTAIRE LOGISTIQUE",
    expensesDocumentTitle: "DÉPENSES MENSUELLES",
    printedOn: "Imprimé le",
    printedTotalItems: "Articles au total",
    printedTotalLines: "Lignes d'inventaire",
    printedTotalExpenses: "Total des dépenses du mois",
    filteredNotice: "Ceci est une sélection filtrée, pas l'inventaire complet.",
    nothingToPrint: "Il n'y a rien à imprimer pour cette sélection.",
    deleteItem: "Supprimer l'article",
    deleteItemBody: "{name} quitte immédiatement l'inventaire et tous les totaux. Sa trace reste dans le journal d'audit.",
    deleteExpense: "Supprimer la dépense",
    deleteExpenseBody: "{name} quitte immédiatement le total du mois. Sa trace reste dans le journal d'audit.",
    itemDeleted: "Article retiré",
    expenseDeleted: "Dépense retirée",
    itemAdded: "Article ajouté",
    itemSaved: "Article enregistré",
    expenseAdded: "Dépense enregistrée",
    expenseSaved: "Dépense enregistrée",
    categoryAdded: "Catégorie ajoutée",
    roomAdded: "Salle ajoutée",
    sectionItem: "L'article",
    sectionPurchase: "Achat et identification",
    sectionExpense: "La dépense",
    sectionFiling: "Classement",
  },
  perms: {
    groupUsers: "Personnes & accès",
    groupCatalogue: "Catalogue",
    groupEnrollment: "Inscription",
    groupMoney: "Argent",
    groupEngagement: "Relation",
    groupOversight: "Contrôle",
    "user.view": "Voir les personnes",
    "user.create": "Créer des comptes",
    "user.update": "Modifier les personnes",
    "user.deactivate": "Désactiver des comptes",
    "user.reset_password": "Réinitialiser des mots de passe",
    "user.assign_role": "Attribuer des rôles",
    "role.manage": "Gérer les rôles et les permissions",
    "course.view": "Voir les formations",
    "course.create": "Créer des formations",
    "course.update": "Modifier des formations",
    "course.archive": "Archiver des formations",
    "course.assign_professor": "Attribuer des formateurs",
    "schedule.view": "Voir le planning",
    "schedule.manage": "Gérer le planning",
    "enrollment.view": "Voir les inscriptions",
    "enrollment.create": "Inscrire des stagiaires",
    "enrollment.update": "Modifier des inscriptions",
    "enrollment.cancel": "Annuler des inscriptions",
    "assessment.view": "Voir les évaluations",
    "assessment.manage": "Créer et modifier des évaluations",
    "score.view": "Voir les notes",
    "score.enter": "Saisir et corriger des notes",
    "score.publish": "Publier les notes aux stagiaires",
    "payment.view": "Voir les paiements",
    "payment.create": "Enregistrer des paiements",
    "payment.approve": "Valider des paiements",
    "payment.reject": "Refuser des paiements",
    "payment.cancel": "Annuler des paiements en attente",
    "proof.upload": "Joindre des justificatifs",
    "proof.view": "Ouvrir des justificatifs",
    "review.create": "Écrire un avis",
    "review.view": "Voir les avis",
    "review.moderate": "Modérer les avis",
    "notification.send": "Envoyer des notifications",
    "report.view_operational": "Lancer des rapports opérationnels",
    "report.view_financial": "Lancer des rapports financiers",
    "report.export": "Exporter des rapports",
    "audit.view": "Lire le journal d'audit",
    "settings.manage": "Gérer les paramètres du système",
    groupLogistics: "Logistique",
    "logistics.view": "Voir l'inventaire",
    "logistics.manage": "Ajouter, modifier et retirer du matériel",
    "expense.view": "Voir les dépenses",
    "expense.manage": "Enregistrer et modifier les dépenses",
    groupAttendance: "Présences",
    "attendance.view": "Voir les feuilles de présence",
    "attendance.record": "Faire et corriger l'appel",
  },
};
