# Generated by Django 5.2.17 on 2026-08-24 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='1 to 5.')),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting moderation'), ('APPROVED', 'Approved'), ('HIDDEN', 'Hidden'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('admin_response', models.TextField(blank=True, help_text='Published alongside an approved review.')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='enrollments.enrollment')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews_review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='reviews_rev_status_70a1f9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_in_range'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['APPROVED', 'HIDDEN', 'REJECTED']), _negated=True), ('moderated_at__isnull', False), _connector='OR'), name='moderated_review_has_a_timestamp')],
            },
        ),
    ]
