# Generated by Django 5.2.17 on 2026-08-24 17:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('report_name', models.CharField(db_index=True, max_length=32)),
                ('fmt', models.CharField(default='csv', max_length=8)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Queued'), ('RUNNING', 'Running'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=8)),
                ('storage_key', models.CharField(blank=True, max_length=500)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_export',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requested_by', '-created_at'], name='reports_exp_request_4e1e8a_idx')],
            },
        ),
    ]
